import { ChunkItem } from "./types";

export const CHUNKS_DATA: readonly ChunkItem[] = [
  {
    "id": "chunk-1",
    "text": "The thing is, [X]...",
    "clean": "The thing is,",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Дело в том, что [X]...",
    "exEn": "The thing is, we don't have enough test coverage for this module.",
    "exRu": "Дело в том, что у нас недостаточно тестового покрытия для этого модуля.",
    "note": "Идеально для объяснения истинной причины проблемы"
  },
  {
    "id": "chunk-2",
    "text": "It's only a matter of time before [X]...",
    "clean": "It's only a matter of time before",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Это лишь вопрос времени, когда [X]...",
    "exEn": "It's only a matter of time before this database crashes under load.",
    "exRu": "Это лишь вопрос времени, когда база упадет под нагрузкой.",
    "note": "Предупреждение о неизбежных рисках"
  },
  {
    "id": "chunk-3",
    "text": "What I'm trying to get at is [X]...",
    "clean": "What I'm trying to get at is",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Что я пытаюсь сказать, так это [X]...",
    "exEn": "What I'm trying to get at is that we need a simpler architecture.",
    "exRu": "Что я пытаюсь сказать — нам нужна архитектура попроще.",
    "note": "Фокусировка мысли после длинного рассуждения"
  },
  {
    "id": "chunk-4",
    "text": "There's no point in [verb-ing]...",
    "clean": "There's no point in",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Нет никакого смысла делать [X]...",
    "exEn": "There's no point in optimizing this query before we have production metrics.",
    "exRu": "Нет смысла оптимизировать этот запрос, пока нет метрик из прода.",
    "note": "Экономия времени от лишней работы"
  },
  {
    "id": "chunk-5",
    "text": "From what I can tell, [X]...",
    "clean": "From what I can tell,",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Насколько я могу судить / по моим наблюдениям, [X]...",
    "exEn": "From what I can tell, the API is behaving normally now.",
    "exRu": "Судя по всему, API сейчас ведет себя нормально.",
    "note": "Оценка ситуации без излишней категоричности"
  },
  {
    "id": "chunk-6",
    "text": "As far as I'm concerned, [X]...",
    "clean": "As far as I'm concerned,",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Что касается меня / на мой взгляд, [X]...",
    "exEn": "As far as I'm concerned, this PR is ready to merge.",
    "exRu": "Что касается меня, этот PR готов к мёрджу.",
    "note": "Четкое выражение личной позиции"
  },
  {
    "id": "chunk-7",
    "text": "It all comes down to [X]...",
    "clean": "It all comes down to",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Всё сводится к [X]...",
    "exEn": "At the end of the day, it all comes down to developer bandwidth.",
    "exRu": "В конечном счете всё сводится к ресурсу разработчиков.",
    "note": "Выделение фундаментального фактора"
  },
  {
    "id": "chunk-8",
    "text": "Chances are, [X]...",
    "clean": "Chances are,",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Весьма вероятно, что [X]...",
    "exEn": "Chances are, the user will never trigger this edge case.",
    "exRu": "Скорее всего, пользователь никогда не вызовет этот редкий кейс.",
    "note": "Естественная замена слову 'probably'"
  },
  {
    "id": "chunk-9",
    "text": "Correct me if I'm wrong, but [X]...",
    "clean": "Correct me if I'm wrong, but",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Поправьте меня, если я ошибаюсь, но [X]...",
    "exEn": "Correct me if I'm wrong, but didn't we agree to ship this next week?",
    "exRu": "Поправьте, если я не прав, но разве мы не договаривались выкатить это на следующей неделе?",
    "note": "Вежливое напоминание о договоренностях"
  },
  {
    "id": "chunk-10",
    "text": "Would you mind if I [past-verb]...?",
    "clean": "Would you mind if I",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Ты не против, если я [X]...?",
    "exEn": "Would you mind if I took over this ticket today?",
    "exRu": "Ты не против, если я заберу этот таск себе?",
    "note": "Максимально вежливый запрос разрешения"
  },
  {
    "id": "chunk-11",
    "text": "The bottom line is that [X]...",
    "clean": "The bottom line is that",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Главная суть в том, что [X]...",
    "exEn": "The bottom line is that our current cloud bill is unsustainable.",
    "exRu": "Суть в том, что текущий счет за облако мы не потянем.",
    "note": "Резюме бизнес-реальности"
  },
  {
    "id": "chunk-12",
    "text": "It turns out that [X]...",
    "clean": "It turns out that",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Оказывается, что [X]...",
    "exEn": "It turns out that the redis cluster was dropping connections.",
    "exRu": "Оказывается, редис-кластер сбрасывал соединения.",
    "note": "Сообщение о вновь выясненных фактах"
  },
  {
    "id": "chunk-13",
    "text": "It goes without saying that [X]...",
    "clean": "It goes without saying that",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Само собой разумеется, что [X]...",
    "exEn": "It goes without saying that user privacy is our top priority.",
    "exRu": "Само собой, приватность пользователей — наш главный приоритет.",
    "note": "Подтверждение очевидной истины"
  },
  {
    "id": "chunk-14",
    "text": "I wouldn't be surprised if [X]...",
    "clean": "I wouldn't be surprised if",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Я не удивлюсь, если [X]...",
    "exEn": "I wouldn't be surprised if the client asks for extra scope.",
    "exRu": "Я не удивлюсь, если клиент попросит дополнительный скоуп.",
    "note": "Прогноз реалистичного развития событий"
  },
  {
    "id": "chunk-15",
    "text": "It's worth pointing out that [X]...",
    "clean": "It's worth pointing out that",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Стоит обратить внимание на то, что [X]...",
    "exEn": "It's worth pointing out that this library hasn't been updated in two years.",
    "exRu": "Стоит отметить, что эта библиотека не обновлялась два года.",
    "note": "Фокусировка внимания на важной детали"
  },
  {
    "id": "chunk-16",
    "text": "Given that [X], we should...",
    "clean": "Given that",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Учитывая, что [X], нам стоит...",
    "exEn": "Given that we have a tight deadline, we should stick to an MVP.",
    "exRu": "Учитывая сжатые сроки, нам стоит ограничиться MVP.",
    "note": "Логический вывод на основе вводных данных"
  },
  {
    "id": "chunk-17",
    "text": "In light of [X],...",
    "clean": "In light of",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "В свете [событий/фактов X]...",
    "exEn": "In light of recent security reports, we need to rotate all secrets.",
    "exRu": "В свете последних отчетов по безопасности, нам нужно сменить все ключи.",
    "note": "Обоснование срочных действий"
  },
  {
    "id": "chunk-18",
    "text": "There's a good chance that [X]...",
    "clean": "There's a good chance that",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Высока вероятность того, что [X]...",
    "exEn": "There's a good chance that the network timeout caused this error.",
    "exRu": "Высока вероятность, что эту ошибку вызвал таймаут сети.",
    "note": "Оценка правдоподобной гипотезы"
  },
  {
    "id": "chunk-19",
    "text": "It remains to be seen whether [X]...",
    "clean": "It remains to be seen whether",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "Еще предстоит увидеть, сработает ли [X]...",
    "exEn": "It remains to be seen whether this migration improves latency.",
    "exRu": "Еще предстоит увидеть, улучшит ли эта миграция задержки.",
    "note": "Когда результат пока не ясен"
  },
  {
    "id": "chunk-20",
    "text": "For the time being, [X]...",
    "clean": "For the time being,",
    "cat": "frames",
    "catName": "Рамка со слотом",
    "trans": "На данный момент / пока что [X]...",
    "exEn": "For the time being, let's keep the fallback mechanism enabled.",
    "exRu": "Пока что давайте оставим резервный механизм включенным.",
    "note": "Временное рабочее решение"
  },
  {
    "id": "chunk-21",
    "text": "take a hit",
    "clean": "take a hit",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Пострадать / просесть / принять удар",
    "exEn": "If we rush this out, testing will definitely <strong>take a hit</strong>.",
    "exRu": "Если мы поторопимся с релизом, тестирование точно пострадает.",
    "note": "Вместо тяжелого 'suffer degradation'"
  },
  {
    "id": "chunk-22",
    "text": "cut corners",
    "clean": "cut corners",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Делать тяп-ляп / срезать углы / экономить на качестве",
    "exEn": "We can't afford to <strong>cut corners</strong> on user authentication.",
    "exRu": "Мы не можем позволить себе срезать углы на авторизации пользователей.",
    "note": "Очень часто звучит при обсуждении техдолга"
  },
  {
    "id": "chunk-23",
    "text": "move the needle",
    "clean": "move the needle",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Принести ощутимый результат / сдвинуть дело с мертвой точки",
    "exEn": "Will this minor UI change actually <strong>move the needle</strong> for retention?",
    "exRu": "Сдвинет ли это мелкое изменение в UI реальные показатели удержания?",
    "note": "Золотой чанк продуктовых и бизнес-митингов"
  },
  {
    "id": "chunk-24",
    "text": "table this for now",
    "clean": "table this for now",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Отложить этот вопрос / перенести на потом",
    "exEn": "Let's <strong>table this for now</strong> and focus on the deployment blocker.",
    "exRu": "Давайте отложим это пока и сфокусируемся на блокерах релиза.",
    "note": "Остановка оффтопа на митинге"
  },
  {
    "id": "chunk-25",
    "text": "circle back to [X]",
    "clean": "circle back to",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Вернуться к теме позже",
    "exEn": "Let's <strong>circle back to</strong> caching strategy at the end of the sync.",
    "exRu": "Давайте вернемся к стратегии кэширования в конце созвона.",
    "note": "Мягкий перенос обсуждения"
  },
  {
    "id": "chunk-26",
    "text": "keep someone in the loop",
    "clean": "keep me in the loop",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Держать в курсе событий",
    "exEn": "Please <strong>keep me in the loop</strong> once the PR is approved.",
    "exRu": "Держи меня в курсе, когда PR аппрувнут.",
    "note": "Стандартная фраза в Slack/созвонах"
  },
  {
    "id": "chunk-27",
    "text": "call the shots",
    "clean": "call the shots",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Принимать решения / руководить процессом",
    "exEn": "The security team <strong>calls the shots</strong> on token expiration.",
    "exRu": "Команда безопасности принимает финальное решение по срокам жизни токенов.",
    "note": "О зонах ответственности"
  },
  {
    "id": "chunk-28",
    "text": "iron out the kinks",
    "clean": "iron out the kinks",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Устранить мелкие шероховатости / отладить детали",
    "exEn": "We just need one more day to <strong>iron out the kinks</strong> in staging.",
    "exRu": "Нам нужен еще один день, чтобы устранить шероховатости на стейджинге.",
    "note": "Перед финальным релизом"
  },
  {
    "id": "chunk-29",
    "text": "get bogged down in [X]",
    "clean": "get bogged down in",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Увязнуть в рутине / закопаться в мелочах",
    "exEn": "Let's not <strong>get bogged down in</strong> edge cases during the initial MVP.",
    "exRu": "Давайте не закапываться в редкие краевые кейсы на этапе первого MVP.",
    "note": "Защита фокуса команды"
  },
  {
    "id": "chunk-30",
    "text": "run into a roadblock",
    "clean": "run into a roadblock",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Натолкнуться на непреодолимое препятствие / застрять",
    "exEn": "We <strong>ran into a roadblock</strong> with the third-party payment gateway.",
    "exRu": "Мы натолкнулись на глухой блокер с платежным шлюзом.",
    "note": "Отчет о блокерах на стендапе"
  },
  {
    "id": "chunk-31",
    "text": "be short on bandwidth",
    "clean": "be short on bandwidth",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Не иметь достаточного ресурса / времени / свободных рук",
    "exEn": "The mobile team is <strong>short on bandwidth</strong> this sprint.",
    "exRu": "У мобильной команды в этом спринте не хватает ресурса.",
    "note": "Bandwidth в IT — рабочее время человека"
  },
  {
    "id": "chunk-32",
    "text": "a slippery slope",
    "clean": "a slippery slope",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Скользкая дорожка / рискованный компромисс",
    "exEn": "Deploying code without automated tests is <strong>a slippery slope</strong>.",
    "exRu": "Деплоить код без автотестов — скользкая дорожка.",
    "note": "Аргумент против сомнительных решений"
  },
  {
    "id": "chunk-33",
    "text": "ballpark estimate",
    "clean": "ballpark estimate",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Приблизительная оценка навскидку",
    "exEn": "Can you give me a rough <strong>ballpark estimate</strong> before we commit?",
    "exRu": "Можешь дать примерную оценку навскидку, прежде чем мы закоммитимся?",
    "note": "Когда не требуют точных часов"
  },
  {
    "id": "chunk-34",
    "text": "touch base on [X]",
    "clean": "touch base on",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Кратко созвониться / сверить часы по вопросу",
    "exEn": "Let's <strong>touch base on</strong> this tomorrow morning.",
    "exRu": "Давай кратко созвонимся и сверимся по этому поводу завтра утром.",
    "note": "Быстрый синк на 5 минут"
  },
  {
    "id": "chunk-35",
    "text": "bring someone up to speed",
    "clean": "bring you up to speed",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Ввести в курс дела",
    "exEn": "Let me <strong>bring you up to speed</strong> on where we stand with the migration.",
    "exRu": "Давай я быстро введу тебя в курс дела по текущему статусу миграции.",
    "note": "Начало онбординга или апдейта"
  },
  {
    "id": "chunk-36",
    "text": "double down on [X]",
    "clean": "double down on",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Удвоить усилия в направлении / сделать ставку на",
    "exEn": "We should <strong>double down on</strong> test automation this quarter.",
    "exRu": "Нам стоит удвоить усилия по автоматизации тестирования в этом квартале.",
    "note": "Стратегический приоритет"
  },
  {
    "id": "chunk-37",
    "text": "walk someone through [X]",
    "clean": "walk you through",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Пошагово показать / провести по коду или процессу",
    "exEn": "Let me share my screen and <strong>walk you through</strong> the new PR.",
    "exRu": "Давай я расшарю экран и пошагово проведу тебя по новому PR.",
    "note": "Идеально для код-ревью и демо"
  },
  {
    "id": "chunk-38",
    "text": "wrap this up",
    "clean": "wrap this up",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Закругляться / подводить итоги созвона",
    "exEn": "We have two minutes left, so let's <strong>wrap this up</strong>.",
    "exRu": "У нас осталось две минуты, так что давайте закругляться.",
    "note": "Завершение встречи вовремя"
  },
  {
    "id": "chunk-39",
    "text": "back to the drawing board",
    "clean": "back to the drawing board",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Начать всё сначала с нуля (после провала идеи)",
    "exEn": "The load test failed completely, so it's <strong>back to the drawing board</strong>.",
    "exRu": "Нагрузочный тест полностью провалился, так что начинаем с нуля.",
    "note": "Когда архитектурная идея не взлетела"
  },
  {
    "id": "chunk-40",
    "text": "quick fix / band-aid solution",
    "clean": "band-aid solution",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Временная заплатка / костыль",
    "exEn": "Restarting the container is just a <strong>band-aid solution</strong>, not a real fix.",
    "exRu": "Перезапуск контейнера — это лишь временный костыль, а не решение.",
    "note": "Обозначение техдолга"
  },
  {
    "id": "chunk-41",
    "text": "root cause",
    "clean": "root cause",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Первопричина сбоя или бага",
    "exEn": "We patched the symptom, but we still haven't found the <strong>root cause</strong>.",
    "exRu": "Мы убрали симптом, но так и не нашли истинную первопричину.",
    "note": "При разборе инцидентов (post-mortem)"
  },
  {
    "id": "chunk-42",
    "text": "rule out [X]",
    "clean": "rule out",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Исключить вариант / гипотезу",
    "exEn": "We can <strong>rule out</strong> database issues — queries are executing in 5ms.",
    "exRu": "Мы можем исключить проблемы с базой — запросы выполняются за 5мс.",
    "note": "В процессе дебага"
  },
  {
    "id": "chunk-43",
    "text": "on the same page",
    "clean": "on the same page",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Одинаково понимать задачу / быть синхронизированными",
    "exEn": "Just to make sure we're all <strong>on the same page</strong>, here's the plan.",
    "exRu": "Просто чтобы убедиться, что мы все на одной волне — вот наш план.",
    "note": "Сверка контекста команды"
  },
  {
    "id": "chunk-44",
    "text": "buy into [X]",
    "clean": "buy into",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Поверить в идею / поддержать подход",
    "exEn": "The stakeholders completely <strong>bought into</strong> our new roadmap.",
    "exRu": "Стейкхолдеры полностью поддержали наш новый роадмап.",
    "note": "Принятие решения руководством"
  },
  {
    "id": "chunk-45",
    "text": "drill down into [X]",
    "clean": "drill down into",
    "cat": "work",
    "catName": "Работа & Созвоны",
    "trans": "Углубиться в конкретные технические детали",
    "exEn": "Let's <strong>drill down into</strong> the network traces to see the delay.",
    "exRu": "Давайте углубимся в сетевые трейсы, чтобы увидеть причину задержки.",
    "note": "Переход к детальному анализу"
  },
  {
    "id": "chunk-46",
    "text": "That's a valid point to raise...",
    "clean": "That's a valid point to raise,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Это очень справедливый вопрос...",
    "exEn": "That's a valid point to raise, and looking at the system requirements...",
    "exRu": "Это справедливый вопрос, и если посмотреть на системные требования...",
    "note": "Дает 2.5 секунды тишины в начале ответа"
  },
  {
    "id": "chunk-47",
    "text": "If we look at the bigger picture...",
    "clean": "If we look at the bigger picture,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Если взглянуть на картину в целом...",
    "exEn": "If we look at the bigger picture, this refactoring pays off in six months.",
    "exRu": "Если взглянуть шире, этот рефакторинг окупится за полгода.",
    "note": "Переход от деталей к стратегии"
  },
  {
    "id": "chunk-48",
    "text": "Off the top of my head,...",
    "clean": "Off the top of my head,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Навскидку / первое, что приходит в голову...",
    "exEn": "Off the top of my head, we’re looking at roughly two weeks of work.",
    "exRu": "Навскидку — тут около двух недель работы.",
    "note": "Защита от требования мгновенной точности"
  },
  {
    "id": "chunk-49",
    "text": "How can I best put this...",
    "clean": "How can I best put this...",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Как бы лучше это сформулировать...",
    "exEn": "How can I best put this... the architecture itself is solid, but the execution was rushed.",
    "exRu": "Как бы лучше сказать... сама архитектура добротная, но реализована в спешке.",
    "note": "Вместо мычания «ээээ»"
  },
  {
    "id": "chunk-50",
    "text": "The technical term escapes me, but...",
    "clean": "The technical term escapes me, but",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Технический термин вылетел из головы, но...",
    "exEn": "The exact term escapes me, but basically it’s a buffer between services.",
    "exRu": "Точный термин вылетел из головы, но по сути это буфер между сервисами.",
    "note": "Вход в серкумлокуцию (описание забытого слова)"
  },
  {
    "id": "chunk-51",
    "text": "What this really boils down to is...",
    "clean": "What this really boils down to is",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "То, к чему всё на самом деле сводится...",
    "exEn": "What this really boils down to is whether we prioritize speed or stability.",
    "exRu": "К чему всё реально сводится — выбираем ли мы скорость или стабильность.",
    "note": "Концентрация сути без задержек"
  },
  {
    "id": "chunk-52",
    "text": "Scratch that — what I meant was...",
    "clean": "Scratch that, what I meant was",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Забудьте / точнее, я имел в виду...",
    "exEn": "Scratch that — what I meant was the staging environment, not production.",
    "exRu": "Сброс — я имел в виду стейджинг, а не прод.",
    "note": "Быстрое исправление оговорки"
  },
  {
    "id": "chunk-53",
    "text": "To put it in perspective,...",
    "clean": "To put it in perspective,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Чтобы было понятно масштабы / для сравнения...",
    "exEn": "To put it in perspective, that outage cost us less than 100 dollars.",
    "exRu": "Чтобы понимать масштаб — тот сбой стоил нам меньше ста долларов.",
    "note": "Сравнение метрик"
  },
  {
    "id": "chunk-54",
    "text": "Bear with me for a second,...",
    "clean": "Bear with me for a second,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Подождите одну секунду (пока ищу ссылку/лог)...",
    "exEn": "<strong>Bear with me for a second</strong> while I pull up the error dashboard.",
    "exRu": "Секунду терпения, пока я открою дашборд с ошибками.",
    "note": "Когда нужно кликнуть ссылку без неловкого молчания"
  },
  {
    "id": "chunk-55",
    "text": "Let's put it this way,...",
    "clean": "Let's put it this way,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Скажем так / сформулируем это следующим образом...",
    "exEn": "<strong>Let's put it this way</strong>: if this script fails, we have no backup.",
    "exRu": "Скажем так: если этот скрипт упадет, бэкапа у нас нет.",
    "note": "Перед прямым или жестким тезисом"
  },
  {
    "id": "chunk-56",
    "text": "If memory serves me right,...",
    "clean": "If memory serves me right,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Если мне не изменяет память...",
    "exEn": "<strong>If memory serves me right</strong>, we hit a similar bug three months ago.",
    "exRu": "Если память мне не изменяет, мы натыкались на похожий баг три месяца назад.",
    "note": "Отсылка к прошлому опыту"
  },
  {
    "id": "chunk-57",
    "text": "In other words,...",
    "clean": "In other words,",
    "cat": "time-buyers",
    "catName": "Покупка времени",
    "trans": "Другими словами / иначе говоря...",
    "exEn": "<strong>In other words</strong>, we need to rewrite this from scratch.",
    "exRu": "Другими словами, нам нужно переписать это с нуля.",
    "note": "Упрощение сложного технического вывода"
  },
  {
    "id": "chunk-58",
    "text": "I see where you're coming from, but...",
    "clean": "I see where you're coming from, but",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Я понимаю логику вашей мысли, но...",
    "exEn": "I see where you're coming from, but latency might double under peak load.",
    "exRu": "Я понимаю, почему ты так предлагаешь, но задержка может удвоиться под пиковой нагрузкой.",
    "note": "Самое нативное вежливое несогласие"
  },
  {
    "id": "chunk-59",
    "text": "I'm not so sure about that...",
    "clean": "I'm not so sure about that",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Я не особо в этом уверен...",
    "exEn": "I'm not so sure about that — we tried that library last year and it had memory leaks.",
    "exRu": "Я не особо в этом уверен — мы пробовали ту либу в прошлом году, и там текли ресурсы.",
    "note": "Мягкий скепсис"
  },
  {
    "id": "chunk-60",
    "text": "It might be a bit of a stretch...",
    "clean": "It might be a bit of a stretch",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Это может быть чересчур амбициозно / на грани возможностей...",
    "exEn": "Delivering both features by Friday might be a bit of a stretch.",
    "exRu": "Сдать обе фичи к пятнице — это, пожалуй, чересчур оптимистично.",
    "note": "Вежливый отказ от нереального дедлайна"
  },
  {
    "id": "chunk-61",
    "text": "Don't get me wrong,...",
    "clean": "Don't get me wrong,",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Не поймите меня неправильно...",
    "exEn": "Don't get me wrong, the design is great, but the backend isn't ready for it.",
    "exRu": "Не поймите неправильно, дизайн отличный, но бэкенд под него ещё не готов.",
    "note": "Защита от обиды собеседника"
  },
  {
    "id": "chunk-62",
    "text": "It's a tough call...",
    "clean": "It's a tough call",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Это сложный и неоднозначный выбор...",
    "exEn": "Whether to rewrite or patch is a tough call.",
    "exRu": "Переписывать с нуля или латать дальше — сложный выбор.",
    "note": "Когда нет очевидно правильного решения"
  },
  {
    "id": "chunk-63",
    "text": "I have mixed feelings about [X]...",
    "clean": "I have mixed feelings about",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "У меня двоякие ощущения насчет [X]...",
    "exEn": "I have mixed feelings about moving our monolith to microservices right now.",
    "exRu": "У меня двоякие ощущения насчет распила монолита на микросервисы прямо сейчас.",
    "note": "Взвешенная осторожность"
  },
  {
    "id": "chunk-64",
    "text": "I'm not entirely convinced that...",
    "clean": "I'm not entirely convinced that",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Я не до конца убежден, что...",
    "exEn": "I'm not entirely convinced that this framework will solve our bottlenecks.",
    "exRu": "Я не до конца убежден, что этот фреймворк решит наши узкие места.",
    "note": "Зрелое инженерное сомнение"
  },
  {
    "id": "chunk-65",
    "text": "Could you unpack that a bit more?",
    "clean": "Could you unpack that a bit more?",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Можешь раскрыть эту мысль подробнее?",
    "exEn": "Could you unpack that last point about authentication flows a bit more?",
    "exRu": "Можешь чуть подробнее развернуть тот последний пункт про сценарии авторизации?",
    "note": "Вместо резкого 'I don't understand'"
  },
  {
    "id": "chunk-66",
    "text": "Spot on!",
    "clean": "Spot on!",
    "cat": "hedging",
    "catName": "Дипломатия & Согласие",
    "trans": "В самую точку! / В яблочко!",
    "exEn": "Your analysis of the deadlock was <strong>spot on</strong>.",
    "exRu": "Твой анализ причин взаимной блокировки попал в самую точку.",
    "note": "Полное и восторженное согласие"
  },
  {
    "id": "chunk-67",
    "text": "Couldn't agree more!",
    "clean": "Couldn't agree more!",
    "cat": "hedging",
    "catName": "Дипломатия & Согласие",
    "trans": "Абсолютно согласен! / Не могу не согласиться!",
    "exEn": "I <strong>couldn't agree more</strong> — simplifying the API is our best bet.",
    "exRu": "Абсолютно согласен — упрощение API сейчас наш лучший шаг.",
    "note": "Быстрое подтверждение единодушия"
  },
  {
    "id": "chunk-68",
    "text": "Fair enough.",
    "clean": "Fair enough.",
    "cat": "hedging",
    "catName": "Дипломатия & Согласие",
    "trans": "Справедливо. / Принимается. / Логично.",
    "exEn": "You want more tests before merging? <strong>Fair enough</strong>, I'll add them.",
    "exRu": "Хочешь больше тестов перед мёрджем? Справедливо, сейчас допишу.",
    "note": "Спокойное принятие аргумента коллеги"
  },
  {
    "id": "chunk-69",
    "text": "Play devil's advocate",
    "clean": "play devil's advocate",
    "cat": "hedging",
    "catName": "Дипломатия & Сомнения",
    "trans": "Побыть адвокатом дьявола (покритиковать для проверки)",
    "exEn": "Just to <strong>play devil's advocate</strong>, what happens if AWS goes down?",
    "exRu": "Просто побуду адвокатом дьявола: а что будет, если ляжет AWS?",
    "note": "Безопасный способ задать неудобный вопрос"
  },
  {
    "id": "chunk-70",
    "text": "At the end of the day,...",
    "clean": "At the end of the day,",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "В конечном счете / в сухом остатке...",
    "exEn": "At the end of the day, users only care if the app is fast and reliable.",
    "exRu": "В конечном счете пользователям важно только то, чтобы приложение работало быстро и стабильно.",
    "note": "Самый частый чанк американского английского"
  },
  {
    "id": "chunk-71",
    "text": "Long story short,...",
    "clean": "Long story short,",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Короче говоря / если в двух словах...",
    "exEn": "Long story short, we had to roll back the migration.",
    "exRu": "Короче говоря, нам пришлось откатить миграцию.",
    "note": "Переход сразу к финалу истории"
  },
  {
    "id": "chunk-72",
    "text": "Speaking of which,...",
    "clean": "Speaking of which,",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Кстати об этом / к слову говоря...",
    "exEn": "Speaking of which, did you get a chance to check my pull request?",
    "exRu": "Кстати об этом — у тебя получилось посмотреть мой пулреквест?",
    "note": "Плавный переход на смежную тему"
  },
  {
    "id": "chunk-73",
    "text": "For what it's worth,...",
    "clean": "For what it's worth,",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Если это имеет значение / к слову...",
    "exEn": "For what it's worth, I think you handled that client escalation really well.",
    "exRu": "К слову сказать, я считаю, ты отлично разрулил ту эскалацию с клиентом.",
    "note": "Мягкая поддержка или дополнение"
  },
  {
    "id": "chunk-74",
    "text": "Out of the blue",
    "clean": "out of the blue",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Внезапно / как гром среди ясного неба",
    "exEn": "The server started throwing 500 errors completely out of the blue.",
    "exRu": "Сервер начал сыпать 500-ми ошибками совершенно внезапно.",
    "note": "Неожиданное событие"
  },
  {
    "id": "chunk-75",
    "text": "It is what it is",
    "clean": "It is what it is",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Что есть, то есть / ничего уже не поделаешь",
    "exEn": "We missed the sprint goal, but it is what it is. Let's do better next week.",
    "exRu": "Мы упустили цель спринта, но что поделать. Сделаем лучше на следующей неделе.",
    "note": "Философское принятие факта"
  },
  {
    "id": "chunk-76",
    "text": "Cross that bridge when we come to it",
    "clean": "cross that bridge when we come to it",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Решать проблемы по мере их поступления",
    "exEn": "We might run out of storage in two years, but we'll cross that bridge when we come to it.",
    "exRu": "Возможно, через два года у нас кончится место, но решим эту проблему, когда дойдем до неё.",
    "note": "Отказ от преждевременной паники"
  },
  {
    "id": "chunk-77",
    "text": "Sleep on it",
    "clean": "sleep on it",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Переспать с этой мыслью / принять решение утром",
    "exEn": "Don't accept the offer right away. Sleep on it and let them know tomorrow.",
    "exRu": "Не соглашайся на оффер сразу. Переспи с этой мыслью и ответь им завтра.",
    "note": "Перед важным решением"
  },
  {
    "id": "chunk-78",
    "text": "Hit the ground running",
    "clean": "hit the ground running",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Взяться за дело без раскачки / сразу включиться на полную",
    "exEn": "The new senior developer hit the ground running on day one.",
    "exRu": "Новый сеньор включился в работу на полной скорости с первого же дня.",
    "note": "Высокая продуктивность"
  },
  {
    "id": "chunk-79",
    "text": "No big deal",
    "clean": "No big deal",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Ничего страшного / ерунда / пустяки",
    "exEn": "Don't worry about the typo in Slack, it's <strong>no big deal</strong>.",
    "exRu": "Не переживай из-за опечатки в слаке, это ерунда.",
    "note": "Успокоение собеседника"
  },
  {
    "id": "chunk-80",
    "text": "Fingers crossed",
    "clean": "Fingers crossed",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Держим кулачки / надеемся на удачу",
    "exEn": "We're deploying the hotfix right now. <strong>Fingers crossed</strong>!",
    "exRu": "Мы деплоим хотфикс прямо сейчас. Держим кулачки!",
    "note": "Пожелание успеха перед релизом"
  },
  {
    "id": "chunk-81",
    "text": "In a nutshell,...",
    "clean": "In a nutshell,",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "В двух словах / кратко говоря...",
    "exEn": "<strong>In a nutshell</strong>, our new feature lets users export reports to PDF.",
    "exRu": "В двух словах: наша новая фича позволяет пользователям экспортировать отчеты в PDF.",
    "note": "Краткий синопсис"
  },
  {
    "id": "chunk-82",
    "text": "Call it a day",
    "clean": "call it a day",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Закончить работу на сегодня",
    "exEn": "We've been debugging for eight hours straight. Let's <strong>call it a day</strong>.",
    "exRu": "Мы дебажим восемь часов подряд. Давайте закругляться на сегодня.",
    "note": "Конец рабочего дня"
  },
  {
    "id": "chunk-83",
    "text": "Ring a bell",
    "clean": "ring a bell",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Звучать знакомо / напоминать что-то",
    "exEn": "Does the name of this error class <strong>ring a bell</strong> to anyone?",
    "exRu": "Название этого класса ошибок кому-нибудь о чем-то говорит?",
    "note": "Проверка воспоминаний"
  },
  {
    "id": "chunk-84",
    "text": "Bite the bullet",
    "clean": "bite the bullet",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Стиснуть зубы и сделать тяжелую/неприятную работу",
    "exEn": "We just have to <strong>bite the bullet</strong> and rewrite the legacy parser.",
    "exRu": "Нам просто нужно стиснуть зубы и переписать этот легаси-парсер.",
    "note": "Решимость перед рутиной"
  },
  {
    "id": "chunk-85",
    "text": "Cut to the chase",
    "clean": "cut to the chase",
    "cat": "social",
    "catName": "Живое общение",
    "trans": "Перейти сразу к сути без лишних предисловий",
    "exEn": "Let's <strong>cut to the chase</strong>: how much will this migration cost?",
    "exRu": "Давайте сразу к делу: во сколько нам обойдется эта миграция?",
    "note": "Экономия времени на встречах"
  },
  {
    "id": "chunk-86",
    "text": "make sense",
    "clean": "make sense",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Иметь смысл / звучать логично",
    "exEn": "Does that explanation <strong>make sense</strong>, or should I rephrase?",
    "exRu": "Это объяснение звучит логично, или мне перефразировать?",
    "note": "Никогда не 'have sense'"
  },
  {
    "id": "chunk-87",
    "text": "make sure",
    "clean": "make sure",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Убедиться / проконтролировать",
    "exEn": "Please <strong>make sure</strong> all environment variables are populated.",
    "exRu": "Пожалуйста, убедись, что все переменные окружения заполнены.",
    "note": "Базовая фраза в разработке"
  },
  {
    "id": "chunk-88",
    "text": "take into account",
    "clean": "take into account",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Принимать во внимание / учитывать",
    "exEn": "We need to <strong>take into account</strong> timezone differences across teams.",
    "exRu": "Нам нужно принять во внимание разницу в часовых поясах между командами.",
    "note": "Обязательный рабочий чанк"
  },
  {
    "id": "chunk-89",
    "text": "take advantage of [X]",
    "clean": "take advantage of",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Воспользоваться возможностью / извлечь пользу",
    "exEn": "We should <strong>take advantage of</strong> HTTP/3 to reduce handshake overhead.",
    "exRu": "Нам стоит воспользоваться преимуществами HTTP/3, чтобы снизить оверхед на хэндшейки.",
    "note": "В нейтральном или позитивном ключе"
  },
  {
    "id": "chunk-90",
    "text": "take for granted",
    "clean": "take for granted",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Принимать как само собой разумеющееся",
    "exEn": "We shouldn't <strong>take 99.9% uptime for granted</strong> without automated failover.",
    "exRu": "Не стоит принимать аптайм в 99.9% как должное без настроенного авто-фейловера.",
    "note": "Предостережение от самоуспокоенности"
  },
  {
    "id": "chunk-91",
    "text": "come in handy",
    "clean": "come in handy",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Пригодиться / оказаться полезным",
    "exEn": "This script will definitely <strong>come in handy</strong> during the database migration.",
    "exRu": "Этот скрипт определенно пригодится во время миграции базы данных.",
    "note": "Удобный инструмент"
  },
  {
    "id": "chunk-92",
    "text": "catch someone off guard",
    "clean": "catch off guard",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Застать врасплох",
    "exEn": "The sudden traffic surge <strong>caught our load balancers off guard</strong>.",
    "exRu": "Внезапный всплеск трафика застал наши балансировщики врасплох.",
    "note": "О неожиданных событиях"
  },
  {
    "id": "chunk-93",
    "text": "come to terms with [X]",
    "clean": "come to terms with",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Смириться с фактом / принять неизбежное",
    "exEn": "We have to <strong>come to terms with</strong> the fact that legacy code won't disappear overnight.",
    "exRu": "Придется смириться с тем, что легаси-код не исчезнет за одну ночь.",
    "note": "Принятие реальности"
  },
  {
    "id": "chunk-94",
    "text": "pay off",
    "clean": "pay off",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Окупиться / принести плоды",
    "exEn": "All the effort we put into end-to-end tests really <strong>paid off</strong>.",
    "exRu": "Все усилия, вложенные в сквозные тесты, действительно окупились с лихвой.",
    "note": "Результат долгой работы"
  },
  {
    "id": "chunk-95",
    "text": "have second thoughts",
    "clean": "have second thoughts",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Сомневаться / передумывать / колебаться",
    "exEn": "I'm having <strong>second thoughts</strong> about dropping support for iOS 15.",
    "exRu": "Я начинаю сомневаться насчет прекращения поддержки iOS 15.",
    "note": "Возникновение сомнений"
  },
  {
    "id": "chunk-96",
    "text": "keep in mind",
    "clean": "keep in mind",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Иметь в виду / не забывать о",
    "exEn": "Please <strong>keep in mind</strong> that the staging database resets every Sunday.",
    "exRu": "Имей в виду, что база данных на стейджинге сбрасывается каждое воскресенье.",
    "note": "Полезное напоминание"
  },
  {
    "id": "chunk-97",
    "text": "run out of [X]",
    "clean": "run out of",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Закончиться (о времени, памяти, бюджете, терпении)",
    "exEn": "The service crashed because it <strong>ran out of memory</strong>.",
    "exRu": "Сервис упал, потому что у него закончилась оперативная память.",
    "note": "Физическое исчерпание ресурса"
  },
  {
    "id": "chunk-98",
    "text": "look into [X]",
    "clean": "look into",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Исследовать / разобраться в вопросе",
    "exEn": "I'll <strong>look into</strong> why that webhook failed and update the ticket.",
    "exRu": "Я разберусь, почему упал тот вебхук, и обновлю тикет.",
    "note": "Обещание исследовать проблему"
  },
  {
    "id": "chunk-99",
    "text": "stay on top of [X]",
    "clean": "stay on top of",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Контролировать ситуацию / держать руку на пульсе",
    "exEn": "Our alerts help us <strong>stay on top of</strong> error rate spikes.",
    "exRu": "Наши алерты помогают держать под контролем всплески ошибок.",
    "note": "Проактивный мониторинг"
  },
  {
    "id": "chunk-100",
    "text": "figure out",
    "clean": "figure out",
    "cat": "verbs",
    "catName": "Глагольные коллокации",
    "trans": "Понять / разобраться / докопаться до сути",
    "exEn": "It took us three hours to <strong>figure out</strong> why the build was failing.",
    "exRu": "У нас ушло три часа, чтобы понять, почему ломалась сборка.",
    "note": "Вместо 'understand'"
  }
] as const;
