import { DenseChunkItem } from "./types";

export const DENSE_CHUNKS_DATA: readonly DenseChunkItem[] = [
  // ==========================================
  // TIER 1: Скорая помощь (Оправдания и реальность)
  // ==========================================
  {
    id: "dense-1",
    tier: 1,
    tierName: "Уровень 1: Скорая помощь",
    title: "1. I was supposed to [verb], but...",
    trans: "«Я вообще-то должен был сделать [X], но...»",
    exEn: "I was supposed to pick up my sister from the station, but my car wouldn't start.",
    exRu: "Я должен был встретить сестру с вокзала, но машина наотрез отказалась заводиться.",
    description: "Мгновенное спасение, когда план сорвался по независящим обстоятельствам.",
  },
  {
    id: "dense-2",
    tier: 1,
    tierName: "Уровень 1: Скорая помощь",
    title: "2. We ended up [verb-ing]...",
    trans: "«В итоге всё закончилось тем, что мы...»",
    exEn: "We were looking for an Italian place, but ended up grabbing some quick tacos across the street.",
    exRu: "Мы искали итальянский ресторан, а в итоге просто перекусили тако через дорогу.",
    description: "Показывает незапланированный, но естественный поворот событий.",
  },
  {
    id: "dense-3",
    tier: 1,
    tierName: "Уровень 1: Скорая помощь",
    title: "3. I managed to [verb]...",
    trans: "«Мне всё-таки удалось / получилось [сделать X]...»",
    exEn: "I managed to get tickets for the Saturday show right before they sold out!",
    exRu: "Мне все-таки удалось ухватить билеты на субботний концерт прямо перед тем, как их раскупили!",
    description: "Успех после некоторых сложностей или напряженного ожидания.",
  },
  {
    id: "dense-4",
    tier: 1,
    tierName: "Уровень 1: Скорая помощь",
    title: "4. I didn't mean to [verb]...",
    trans: "«Я не хотел / не имел намерения [обидеть, задеть, сломать]...»",
    exEn: "I didn't mean to wake you up, I was trying to be as quiet as possible.",
    exRu: "Я совершенно не хотел тебя будить, честно старался ходить на цыпочках.",
    description: "Универсальное искреннее извинение за непреднамеренное действие.",
  },
  {
    id: "dense-5",
    tier: 1,
    tierName: "Уровень 1: Скорая помощь",
    title: "5. It took me a while to [verb]...",
    trans: "«У меня ушло довольно много времени на то, чтобы...»",
    exEn: "It took me a while to figure out how this new coffee machine actually works.",
    exRu: "У меня ушла куча времени на то, чтобы разобраться, как вообще работает эта кофемашина.",
    description: "Естественное признание того, что задача потребовала времени.",
  },
  {
    id: "dense-6",
    tier: 1,
    tierName: "Уровень 1: Скорая помощь",
    title: "6. We're about to [verb]...",
    trans: "«Мы вот-вот сделаем / находимся в шаге от...»",
    exEn: "Hold on just a second, we're just about to head out the door.",
    exRu: "Погоди буквально секунду, мы буквально вот-вот выходим из дома.",
    description: "Фраза для действия, которое случится через считанные минуты.",
  },

  // ==========================================
  // TIER 2: Процессы, привычки и задержки
  // ==========================================
  {
    id: "dense-7",
    tier: 2,
    tierName: "Уровень 2: Процессы и привычки",
    title: "7. I haven't gotten around to [verb-ing] yet",
    trans: "«У меня пока руки не дошли до этого»",
    exEn: "I haven't gotten around to organizing those vacation photos yet.",
    exRu: "У меня пока руки не дошли разобрать фотографии из отпуска.",
    description: "Звучит в десять раз естественнее, чем сухое «I didn't have time».",
  },
  {
    id: "dense-8",
    tier: 2,
    tierName: "Уровень 2: Процессы и привычки",
    title: "8. I happened to [verb]...",
    trans: "«Так вышло, что я случайно... / Я как раз случайно...»",
    exEn: "I happened to run into Marcus while I was picking up coffee this morning.",
    exRu: "Я совершенно случайно столкнулся с Маркусом, когда брал утренний кофе.",
    description: "Приятная или полезная случайность без предварительного намерения.",
  },
  {
    id: "dense-9",
    tier: 2,
    tierName: "Уровень 2: Процессы и привычки",
    title: "9. I'm not used to [verb-ing]...",
    trans: "«Я не привык к [X] / Мне пока непривычно делать [X]»",
    exEn: "I'm still not used to waking up at six in the morning.",
    exRu: "Я до сих пор не привык просыпаться в шесть утра.",
    description: "Объяснение дискомфорта или периода адаптации.",
  },
  {
    id: "dense-10",
    tier: 2,
    tierName: "Уровень 2: Процессы и привычки",
    title: "10. I feel like [verb-ing / clause]...",
    trans: "«Мне кажется, что... / Мне охота [сделать что-то]»",
    exEn: "I feel like staying in and ordering pizza tonight instead of going to a noisy party.",
    exRu: "Мне сегодня больше охота остаться дома и заказать пиццу, чем идти на шумную вечеринку.",
    description: "Выражение сиюминутного желания или интуитивного настроения.",
  },
  {
    id: "dense-11",
    tier: 2,
    tierName: "Уровень 2: Процессы и привычки",
    title: "11. What it boils down to is [noun / verb-ing]...",
    trans: "«Вся суть сводится к тому, что...»",
    exEn: "What it boils down to is whether we can find a babysitter for Friday evening.",
    exRu: "Вся суть сводится к тому, найдем ли мы няню на вечер пятницы.",
    description: "Отсечение второстепенных деталей и выход на главное условие.",
  },
  {
    id: "dense-12",
    tier: 2,
    tierName: "Уровень 2: Процессы и привычки",
    title: "12. I'm looking forward to [verb-ing]...",
    trans: "«С нетерпением жду, когда...»",
    exEn: "I'm really looking forward to getting some rest over the weekend.",
    exRu: "Я с огромным нетерпением жду возможности хорошенько выспаться на выходных.",
    description: "Позитивное ожидание приятного события.",
  },

  // ==========================================
  // TIER 3: Тонкая дипломатия и гипотезы
  // ==========================================
  {
    id: "dense-13",
    tier: 3,
    tierName: "Уровень 3: Тонкая дипломатия",
    title: "13. I was wondering if you could [verb]...",
    trans: "«Я хотел поинтересоваться, не мог бы ты...»",
    exEn: "I was wondering if you could help me move this couch into the living room?",
    exRu: "Я хотел спросить, не мог бы ты помочь мне перетащить этот диван в гостиную?",
    description: "Максимально деликатная, уважительная форма просьбы.",
  },
  {
    id: "dense-14",
    tier: 3,
    tierName: "Уровень 3: Тонкая дипломатия",
    title: "14. I can't help but feel that [X]...",
    trans: "«Не могу избавиться от ощущения, что...»",
    exEn: "I can't help but feel that we're rushing into this way too fast.",
    exRu: "Не могу отделаться от ощущения, что мы слишком торопим события.",
    description: "Ненавязчивый способ высказать внутреннее сомнение.",
  },
  {
    id: "dense-15",
    tier: 3,
    tierName: "Уровень 3: Тонкая дипломатия",
    title: "15. We should have [past participle]...",
    trans: "«Нам следовало бы сделать [X] (но мы не сделали)...»",
    exEn: "We really should have checked the weather forecast before setting up the tent.",
    exRu: "Нам действительно следовало глянуть прогноз погоды перед тем, как ставить палатку.",
    description: "Признание ошибки задним числом.",
  },
  {
    id: "dense-16",
    tier: 3,
    tierName: "Уровень 3: Тонкая дипломатия",
    title: "16. Could we have avoided this if we had [past participle]...?",
    trans: "«Могли ли мы этого избежать, если бы поступили иначе?»",
    exEn: "Could we have avoided that huge delay if we had left just twenty minutes earlier?",
    exRu: "Могли ли мы избежать той дикой пробки, если бы выехали всего на 20 минут раньше?",
    description: "Конструктивный разбор полетов без взаимных упреков.",
  },
  {
    id: "dense-17",
    tier: 3,
    tierName: "Уровень 3: Тонкая дипломатия",
    title: "17. If it hadn't been for [X], we would have [past participle]...",
    trans: "«Если бы не [X], мы бы точно...»",
    exEn: "If it hadn't been for that friendly local who pointed us in the right direction, we would've gotten completely lost.",
    exRu: "Если бы не тот дружелюбный местный житель, который подсказал дорогу, мы бы окончательно заблудились.",
    description: "Эмоциональное признание ключевого спасительного фактора.",
  },
  {
    id: "dense-18",
    tier: 3,
    tierName: "Уровень 3: Тонкая дипломатия",
    title: "18. It's not worth [verb-ing]...",
    trans: "«Не стоит тратить нервы / силы на то, чтобы...»",
    exEn: "It's not worth getting into an argument over something so silly.",
    exRu: "Не стоит вступать в спор из-за такой ерунды.",
    description: "Разрешение конфликта и сохранение энергии.",
  },
] as const;
