export type DiscourseBlockId =
  | "positioning"
  | "cohesion"
  | "disagreement"
  | "concession"
  | "maneuvering"
  | "synthesis";

export interface DiscourseChunkItem {
  readonly id: string;
  readonly blockId: DiscourseBlockId;
  readonly blockNameRu: string;
  readonly blockNumber: string;
  readonly frameEn: string;
  readonly authenticExampleEn: string;
  readonly pragmaticFunctionRu: string;
  readonly russianEquivalent: string;
  readonly slotType: string;
  readonly slotSwaps: readonly string[];
  readonly audioText: string;
}

export interface ComparativeRegisterItem {
  readonly id: string;
  readonly functionRu: string;
  readonly basicTemplateB1B2: string;
  readonly advancedFrameC1: string;
  readonly socioPragmaticEffectRu: string;
  readonly basicExample: string;
  readonly advancedExample: string;
}

export interface MethodologyStageItem {
  readonly id: string;
  readonly number: string;
  readonly titleRu: string;
  readonly subtitleRu: string;
  readonly descriptionRu: string;
  readonly keyProtocol: string;
  readonly actionItem: string;
}

export interface DiscourseBlockMeta {
  readonly id: DiscourseBlockId;
  readonly titleRu: string;
  readonly shortTitle: string;
  readonly descriptionRu: string;
  readonly icon: string;
  readonly count: number;
  readonly badgeColor: string;
}

export const DISCOURSE_BLOCKS: readonly DiscourseBlockMeta[] = [
  {
    id: "positioning",
    titleRu: "Ввод позиции и эпистемическая модальность",
    shortTitle: "Ввод позиции",
    descriptionRu: "Точная калибровка личной оценки от субъективного мнения к беспристрастному экспертному тезису.",
    icon: "🎯",
    count: 10,
    badgeColor: "cyan",
  },
  {
    id: "cohesion",
    titleRu: "Аргументативная когезия и развертывание тезиса",
    shortTitle: "Логическая когезия",
    descriptionRu: "Сопряжение разрозненных суждений в монолитную кумулятивную цепочку доказательств.",
    icon: "🔗",
    count: 11,
    badgeColor: "emerald",
  },
  {
    id: "disagreement",
    titleRu: "Прагматически смягченное несогласие",
    shortTitle: "Смягченное несогласие",
    descriptionRu: "Бесконфликтная деконструкция контраргументов с сохранением профессионального партнерства.",
    icon: "🛡️",
    count: 11,
    badgeColor: "amber",
  },
  {
    id: "concession",
    titleRu: "Концессивные структуры и стратегическая уступка",
    shortTitle: "Стратегическая уступка",
    descriptionRu: "Частичное признание правоты оппонента для усиления итогового контртезиса и перехвата инициативы.",
    icon: "🤝",
    count: 10,
    badgeColor: "indigo",
  },
  {
    id: "maneuvering",
    titleRu: "Когнитивное маневрирование и заполнение пауз",
    shortTitle: "Когнитивные паузы",
    descriptionRu: "Получение 1.5–3 секунд времени на обдумывание без дисфлюэнтных междометий и потери контакта.",
    icon: "⏱️",
    count: 10,
    badgeColor: "violet",
  },
  {
    id: "synthesis",
    titleRu: "Метадискурсивное реформулирование и синтез",
    shortTitle: "Синтез и резюме",
    descriptionRu: "Оперативная самокоррекция, верификация логики партнера и компрессионный итог дебатов.",
    icon: "✨",
    count: 11,
    badgeColor: "rose",
  },
] as const;

export const DISCOURSE_CHUNKS: readonly DiscourseChunkItem[] = [
  // BLOCK 1: Ввод позиции и эпистемическая модальность (10 chunks)
  {
    id: "disc-pos-1",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "The way I see it, [clause]",
    authenticExampleEn: "The way I see it, the initiative stalled not from lack of capital, but from flawed execution.",
    pragmaticFunctionRu: "Авторитетное введение целостной персональной оценки ситуации без излишней категоричности.",
    russianEquivalent: "На мой взгляд / Как мне это представляется",
    slotType: "[clause]",
    slotSwaps: [
      "...the initiative stalled not from lack of capital, but from flawed execution.",
      "...our core competitive edge lies in proprietary infrastructure rather than aggressive pricing.",
      "...the architectural overhaul must precede any enterprise feature expansion.",
      "...the delivery bottleneck stems from fragmented stakeholder communication.",
    ],
    audioText: "The way I see it, the initiative stalled not from lack of capital, but from flawed execution.",
  },
  {
    id: "disc-pos-2",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "As far as I am concerned, [clause]",
    authenticExampleEn: "As far as I am concerned, the proposed regulation introduces far too many vulnerabilities.",
    pragmaticFunctionRu: "Обозначение жесткой персональной позиции и четкое разграничение зон ответственности.",
    russianEquivalent: "Что касается меня / Насколько я могу судить",
    slotType: "[clause]",
    slotSwaps: [
      "...the proposed regulation introduces far too many vulnerabilities.",
      "...we have satisfied all Tier-1 SLA criteria under the current contract.",
      "...skipping the penetration testing phase is an unacceptable business hazard.",
      "...the legacy authentication protocol should be deprecated by Q3.",
    ],
    audioText: "As far as I am concerned, the proposed regulation introduces far too many vulnerabilities.",
  },
  {
    id: "disc-pos-3",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "Speaking from personal experience, [clause]",
    authenticExampleEn: "Speaking from personal experience, sudden architectural pivots always create technical debt.",
    pragmaticFunctionRu: "Легитимация тезиса через апелляцию к накопленному профессиональному опыту.",
    russianEquivalent: "Исходя из моего личного опыта",
    slotType: "[clause]",
    slotSwaps: [
      "...sudden architectural pivots always create technical debt.",
      "...rushing client onboarding before data sanitization triggers massive churn.",
      "...distributed teams require asynchronous documentation far more than daily standups.",
      "...monolithic deployments become fragile once engineering scales beyond fifty contributors.",
    ],
    audioText: "Speaking from personal experience, sudden architectural pivots always create technical debt.",
  },
  {
    id: "disc-pos-4",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "If you ask me, [clause]",
    authenticExampleEn: "If you ask me, the platform is already demonstrating clear signs of market fatigue.",
    pragmaticFunctionRu: "Неформальный, но веский маркер критической экспертной оценки положения дел.",
    russianEquivalent: "Если вы спросите мое мнение",
    slotType: "[clause]",
    slotSwaps: [
      "...the platform is already demonstrating clear signs of market fatigue.",
      "...we are heavily over-engineering a feature that fewer than two percent of clients use.",
      "...the marketing budget would yield higher returns if redirected to developer relations.",
      "...the vendor has deprioritized our support tickets in favor of enterprise accounts.",
    ],
    audioText: "If you ask me, the platform is already demonstrating clear signs of market fatigue.",
  },
  {
    id: "disc-pos-5",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "The strongest case, in my view, is for [noun / -ing]",
    authenticExampleEn: "The strongest case, in my view, is for prioritizing client retention over rapid acquisition.",
    pragmaticFunctionRu: "Аналитическое выдвижение наиболее обоснованного стратегического варианта решения.",
    russianEquivalent: "Наиболее убедительным аргументом, на мой взгляд, выступает",
    slotType: "[noun / -ing]",
    slotSwaps: [
      "...prioritizing client retention over rapid acquisition.",
      "...consolidating disparate microservices back into a modular monolith.",
      "...establishing an automated compliance verification gate before deployment.",
      "...investing in observability tooling to curb mean time to recovery.",
    ],
    audioText: "The strongest case, in my view, is for prioritizing client retention over rapid acquisition.",
  },
  {
    id: "disc-pos-6",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "I am inclined to believe that [clause]",
    authenticExampleEn: "I am inclined to believe that the recent drop in performance is structural rather than seasonal.",
    pragmaticFunctionRu: "Эпистемическое смягчение категоричности тезиса в строгом аналитическом контексте.",
    russianEquivalent: "Я склонен полагать, что",
    slotType: "[clause]",
    slotSwaps: [
      "...the recent drop in performance is structural rather than seasonal.",
      "...the conversion slowdown reflects friction in our self-serve checkout pipeline.",
      "...our talent retention issues are rooted in unclear career progression frameworks.",
      "...customer reluctance stems from security governance rather than pricing thresholds.",
    ],
    audioText: "I am inclined to believe that the recent drop in performance is structural rather than seasonal.",
  },
  {
    id: "disc-pos-7",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "My impression is that [clause]",
    authenticExampleEn: "My impression is that the stakeholders have not fully accounted for compliance overheads.",
    pragmaticFunctionRu: "Деликатное выдвижение предварительного наблюдения без прямой конфронтации с коллегами.",
    russianEquivalent: "У меня складывается впечатление, что",
    slotType: "[clause]",
    slotSwaps: [
      "...the stakeholders have not fully accounted for compliance overheads.",
      "...the product roadmap underestimates the migration complexity for legacy databases.",
      "...the client team expects bespoke customizations outside our standard SLA scope.",
      "...management is prioritizing immediate velocity over long-term code maintainability.",
    ],
    audioText: "My impression is that the stakeholders have not fully accounted for compliance overheads.",
  },
  {
    id: "disc-pos-8",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "From an objective standpoint, [clause]",
    authenticExampleEn: "From an objective standpoint, the quarterly metrics do not justify such capital expenditure.",
    pragmaticFunctionRu: "Позиционирование суждения как беспристрастного анализа фактических данных и цифр.",
    russianEquivalent: "С объективной точки зрения",
    slotType: "[clause]",
    slotSwaps: [
      "...the quarterly metrics do not justify such capital expenditure.",
      "...the uptime guarantees offered by the new cloud provider fail to meet our redundancy bar.",
      "...the ROI on custom internal tooling falls far short of available commercial alternatives.",
      "...our unit margins cannot sustain additional price concessions without volume commitments.",
    ],
    audioText: "From an objective standpoint, the quarterly metrics do not justify such capital expenditure.",
  },
  {
    id: "disc-pos-9",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "It seems to me that [clause]",
    authenticExampleEn: "It seems to me that the organization is addressing the symptoms rather than the systemic cause.",
    pragmaticFunctionRu: "Введение рефлексивного суждения с открытостью к конструктивной дискуссии.",
    russianEquivalent: "Мне представляется, что",
    slotType: "[clause]",
    slotSwaps: [
      "...the organization is addressing the symptoms rather than the systemic cause.",
      "...we are attempting to optimize a conversion funnel that suffers from poor product-market fit.",
      "...cross-team silos are causing repetitive re-work in data engineering.",
      "...a hybrid release cadence would mitigate risk without slowing feature turnaround.",
    ],
    audioText: "It seems to me that the organization is addressing the symptoms rather than the systemic cause.",
  },
  {
    id: "disc-pos-10",
    blockId: "positioning",
    blockNameRu: "Ввод позиции и эпистемическая модальность",
    blockNumber: "01",
    frameEn: "I would argue that [clause]",
    authenticExampleEn: "I would argue that operational resilience is fundamentally tied to automated testing.",
    pragmaticFunctionRu: "Формулирование взвешенного академического или представительского делового тезиса.",
    russianEquivalent: "Я бы утверждал, что",
    slotType: "[clause]",
    slotSwaps: [
      "...operational resilience is fundamentally tied to automated testing.",
      "...early architectural rigor saves ten times more engineering hours than premature optimization.",
      "...customer trust is won through transparent post-mortems rather than defensive communication.",
      "...sustainable developer velocity requires zero tolerance for flaky integration suites.",
    ],
    audioText: "I would argue that operational resilience is fundamentally tied to automated testing.",
  },

  // BLOCK 2: Аргументативная когезия и логическое развертывание тезиса (11 chunks)
  {
    id: "disc-coh-1",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "On top of that, [clause]",
    authenticExampleEn: "The deployment pipeline failed, and on top of that, the rollback mechanism was misconfigured.",
    pragmaticFunctionRu: "Введение дополнительного отягчающего или риторически усиливающего фактора.",
    russianEquivalent: "Вдобавок ко всему / Мало того",
    slotType: "[clause]",
    slotSwaps: [
      "...and on top of that, the rollback mechanism was misconfigured.",
      "...on top of that, our database replica failed to achieve read consensus during peak load.",
      "...on top of that, the client withheld payment pending the second security audit.",
      "...on top of that, the release notes omitted three breaking schema modifications.",
    ],
    audioText: "The deployment pipeline failed, and on top of that, the rollback mechanism was misconfigured.",
  },
  {
    id: "disc-coh-2",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "What is more, [clause]",
    authenticExampleEn: "The solution reduces operational latency, and what is more, it slashes hosting expenditure.",
    pragmaticFunctionRu: "Подключение довода более высокого порядка значимости и ценности.",
    russianEquivalent: "Более того / Что еще важнее",
    slotType: "[clause]",
    slotSwaps: [
      "...and what is more, it slashes hosting expenditure by thirty percent.",
      "...what is more, the unified API removes twelve third-party dependencies.",
      "...what is more, automated audit logs satisfy SOC2 compliance out of the box.",
      "...what is more, customer sentiment scores rose within forty-eight hours of launch.",
    ],
    audioText: "The solution reduces operational latency, and what is more, it slashes hosting expenditure.",
  },
  {
    id: "disc-coh-3",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "Not only that, but [clause]",
    authenticExampleEn: "The team missed the quarterly quota. Not only that, but they compromised core documentation.",
    pragmaticFunctionRu: "Риторическое усиление кумулятивного синергетического эффекта двух связанных аргументов.",
    russianEquivalent: "Не только это, но также",
    slotType: "[clause]",
    slotSwaps: [
      "Not only that, but they compromised core architectural documentation.",
      "Not only that, but the API response latency doubled under half the anticipated traffic.",
      "Not only that, but two key enterprise stakeholders declined to renew their contracts.",
      "Not only that, but the refactoring eliminated four major CVE vulnerabilities.",
    ],
    audioText: "The team missed the quarterly quota. Not only that, but they compromised core documentation.",
  },
  {
    id: "disc-coh-4",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "That is precisely why [clause]",
    authenticExampleEn: "Unit economics are deteriorating, and that is precisely why we must reconsider discounting.",
    pragmaticFunctionRu: "Фиксация строгой, неопровержимой причинно-следственной детерминации.",
    russianEquivalent: "Именно поэтому",
    slotType: "[clause]",
    slotSwaps: [
      "...and that is precisely why we must reconsider discounting policies.",
      "...that is precisely why we are introducing automated pre-commit linting gates.",
      "...that is precisely why the board has mandated an immediate freeze on unbudgeted hires.",
      "...that is precisely why our engineering focus has shifted toward zero-trust networking.",
    ],
    audioText: "Unit economics are deteriorating, and that is precisely why we must reconsider discounting.",
  },
  {
    id: "disc-coh-5",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "In addition to this, [clause]",
    authenticExampleEn: "In addition to this, external audits require continuous verification of user credentials.",
    pragmaticFunctionRu: "Формальное расширение доказательной базы в профессиональном экспертном регистре.",
    russianEquivalent: "В дополнение к этому",
    slotType: "[clause]",
    slotSwaps: [
      "In addition to this, external audits require continuous verification of user credentials.",
      "In addition to this, cross-region replication incurs substantial bandwidth egress charges.",
      "In addition to this, customer success reps report recurring confusion around the new billing UI.",
      "In addition to this, the candidate holds deep expertise in distributed consensus protocols.",
    ],
    audioText: "In addition to this, external audits require continuous verification of user credentials.",
  },
  {
    id: "disc-coh-6",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "To illustrate this point, [clause]",
    authenticExampleEn: "To illustrate this point, consider how the migration path was handled in the previous release.",
    pragmaticFunctionRu: "Переход от абстрактного теоретического постулата к наглядному прецеденту.",
    russianEquivalent: "Чтобы проиллюстрировать данный тезис",
    slotType: "[clause]",
    slotSwaps: [
      "To illustrate this point, consider how the migration path was handled in the previous release.",
      "To illustrate this point, let us examine the drop-off rate on step three of onboarding.",
      "To illustrate this point, look at how competitor platforms responded to the same regulatory change.",
      "To illustrate this point, observe the spike in memory consumption during garbage collection cycles.",
    ],
    audioText: "To illustrate this point, consider how the migration path was handled in the previous release.",
  },
  {
    id: "disc-coh-7",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "A case in point is [noun]",
    authenticExampleEn: "User retention depends on performance; a case in point is the immediate impact of latency on churn.",
    pragmaticFunctionRu: "Введение конкретного примера в качестве прямого доказательства выдвинутого правила.",
    russianEquivalent: "Показательным примером здесь служит",
    slotType: "[noun]",
    slotSwaps: [
      "...a case in point is the immediate impact of latency on customer churn.",
      "...a case in point is the sudden collapse of monolithic platforms under holiday shopping spikes.",
      "...a case in point is our recent migration to containerized microservices.",
      "...a case in point is the German regulatory framework regarding data residency.",
    ],
    audioText: "User retention depends on performance; a case in point is the immediate impact of latency on churn.",
  },
  {
    id: "disc-coh-8",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "Looking at the bigger picture, [clause]",
    authenticExampleEn: "Looking at the bigger picture, short-term margin contraction is secondary to ecosystem lock-in.",
    pragmaticFunctionRu: "Изменение масштаба рассмотрения с тактического сиюминутного на макростратегический.",
    russianEquivalent: "Если взглянуть на общую картину",
    slotType: "[clause]",
    slotSwaps: [
      "Looking at the bigger picture, short-term margin contraction is secondary to ecosystem lock-in.",
      "Looking at the bigger picture, temporary operational friction will yield massive compounding velocity.",
      "Looking at the bigger picture, our market dominance hinges on open-source community adoption.",
      "Looking at the bigger picture, quarterly fluctuations pale in comparison to annual platform retention.",
    ],
    audioText: "Looking at the bigger picture, short-term margin contraction is secondary to ecosystem lock-in.",
  },
  {
    id: "disc-coh-9",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "By the same token, [clause]",
    authenticExampleEn: "We expect strict discipline from vendors; by the same token, internal teams must honor SLA windows.",
    pragmaticFunctionRu: "Проведение симметричной логической аналогии между смежными явлениями.",
    russianEquivalent: "Равным образом / По той же логике",
    slotType: "[clause]",
    slotSwaps: [
      "...by the same token, internal teams must honor strict SLA delivery windows.",
      "...by the same token, engineering cannot disregard business metrics in architectural debates.",
      "...by the same token, leadership must provide adequate tooling if they demand zero defect rates.",
      "...by the same token, prospective partners must respect our strict data confidentiality covenants.",
    ],
    audioText: "We expect strict discipline from vendors; by the same token, internal teams must honor SLA windows.",
  },
  {
    id: "disc-coh-10",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "This brings us to the question of [noun]",
    authenticExampleEn: "This brings us to the question of long-term resource availability under sustained peak loads.",
    pragmaticFunctionRu: "Дискурсивное управление фокусом внимания и плавный переход к ключевому вопросу.",
    russianEquivalent: "Это подводит нас к вопросу о",
    slotType: "[noun]",
    slotSwaps: [
      "This brings us to the question of long-term resource availability under sustained peak loads.",
      "This brings us to the question of governance across multi-tenant cloud partitions.",
      "This brings us to the question of sustainable unit pricing once venture subsidies expire.",
      "This brings us to the question of executive accountability in disaster recovery protocols.",
    ],
    audioText: "This brings us to the question of long-term resource availability under sustained peak loads.",
  },
  {
    id: "disc-coh-11",
    blockId: "cohesion",
    blockNameRu: "Аргументативная когезия и развертывание тезиса",
    blockNumber: "02",
    frameEn: "Consequently, [clause]",
    authenticExampleEn: "Technical debt accumulated across modules; consequently, feature delivery ground to a halt.",
    pragmaticFunctionRu: "Обозначение прямого логического результата предшествующего комплекса условий.",
    russianEquivalent: "Следовательно / Как следствие",
    slotType: "[clause]",
    slotSwaps: [
      "...consequently, feature delivery ground to an unacceptable halt.",
      "...consequently, our cloud computing bill escalated beyond forecasted operational thresholds.",
      "...consequently, the customer success team had to escalate the incident directly to tier-three support.",
      "...consequently, the leadership committee voted to postpone the public beta rollout.",
    ],
    audioText: "Technical debt accumulated across modules; consequently, feature delivery ground to a halt.",
  },

  // BLOCK 3: Прагматически смягченное несогласие и деконструкция контраргументов (11 chunks)
  {
    id: "disc-dis-1",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "I take a slightly different view on [noun]",
    authenticExampleEn: "I take a slightly different view on release readiness; the telemetry raises valid concerns.",
    pragmaticFunctionRu: "Бесконфликтное дипломатическое дистанцирование от позиции собеседника.",
    russianEquivalent: "Я смотрю на этот вопрос несколько иначе",
    slotType: "[noun]",
    slotSwaps: [
      "I take a slightly different view on release readiness; the telemetry raises valid concerns.",
      "I take a slightly different view on priority allocation for this upcoming development cycle.",
      "I take a slightly different view on competitive positioning within our enterprise market segment.",
      "I take a slightly different view on third-party vendor consolidation.",
    ],
    audioText: "I take a slightly different view on release readiness; the telemetry raises valid concerns.",
  },
  {
    id: "disc-dis-2",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "I am not entirely convinced that [clause]",
    authenticExampleEn: "I am not entirely convinced that aggressive hiring will rectify our delivery bottlenecks.",
    pragmaticFunctionRu: "Выражение обоснованного экспертного скепсиса относительно выдвинутого решения.",
    russianEquivalent: "Я не вполне убежден в том, что",
    slotType: "[clause]",
    slotSwaps: [
      "I am not entirely convinced that aggressive hiring will rectify our delivery bottlenecks.",
      "I am not entirely convinced that switching to a NoSQL datastore will resolve query timeouts.",
      "I am not entirely convinced that discounting our enterprise tier will accelerate enterprise adoption.",
      "I am not entirely convinced that mandatory office attendance improves engineering output.",
    ],
    audioText: "I am not entirely convinced that aggressive hiring will rectify our delivery bottlenecks.",
  },
  {
    id: "disc-dis-3",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "That is not necessarily the case, because [clause]",
    authenticExampleEn: "Lowering prices might attract volume, but that is not necessarily the case in premium tiers.",
    pragmaticFunctionRu: "Опровержение необоснованной генерализации или ложного умозаключения оппонента.",
    russianEquivalent: "Это далеко не обязательно так, поскольку",
    slotType: "[clause]",
    slotSwaps: [
      "...but that is not necessarily the case in enterprise and premium subscription tiers.",
      "...that is not necessarily the case, because asynchronous communication often reduces latency.",
      "...that is not necessarily the case, because customers value predictability over sheer raw speed.",
      "...that is not necessarily the case, because our automated tests catch regressions before staging.",
    ],
    audioText: "Lowering prices might attract volume, but that is not necessarily the case in premium tiers.",
  },
  {
    id: "disc-dis-4",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "Up to a point, but surely [clause]",
    authenticExampleEn: "Automation cuts overhead up to a point, but surely contextual verification requires humans.",
    pragmaticFunctionRu: "Очерчивание объективных границ применимости аргумента с выдвижением контртезиса.",
    russianEquivalent: "До определенной степени это так, но ведь",
    slotType: "[clause]",
    slotSwaps: [
      "...up to a point, but surely contextual verification requires human subject matter oversight.",
      "...up to a point, but surely enterprise buyers demand dedicated technical account managers.",
      "...up to a point, but surely code linters cannot replace thorough architectural review.",
      "...up to a point, but surely rapid prototyping cannot justify compromising customer data security.",
    ],
    audioText: "Automation cuts overhead up to a point, but surely contextual verification requires humans.",
  },
  {
    id: "disc-dis-5",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "With all due respect, [clause]",
    authenticExampleEn: "With all due respect, that timeline ignores ongoing infrastructure migrations.",
    pragmaticFunctionRu: "Вежливый институциональный маркер перед выдвижением принципиального возражения.",
    russianEquivalent: "При всем уважении",
    slotType: "[clause]",
    slotSwaps: [
      "With all due respect, that timeline ignores ongoing core infrastructure migrations.",
      "With all due respect, the proposed budget leaves zero margin for contingency risks.",
      "With all due respect, that assumption conflicts with the telemetry data from our European servers.",
      "With all due respect, our SLA obligations preclude us from adopting unverified dependencies.",
    ],
    audioText: "With all due respect, that timeline ignores ongoing infrastructure migrations.",
  },
  {
    id: "disc-dis-6",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "I see where you are coming from, but [clause]",
    authenticExampleEn: "I see where you are coming from, but unit economics simply will not scale on that infrastructure.",
    pragmaticFunctionRu: "Демонстрация валидации чужой точки зрения с последующей ее конструктивной нейтрализацией.",
    russianEquivalent: "Я понимаю вашу логику, однако",
    slotType: "[clause]",
    slotSwaps: [
      "I see where you are coming from, but unit economics simply will not scale on that cloud infrastructure.",
      "I see where you are coming from, but our engineering headcount cannot absorb two parallel pilots.",
      "I see where you are coming from, but customer feedback highlights simplicity over feature density.",
      "I see where you are coming from, but delaying the security patch exposes our user data to exploit risks.",
    ],
    audioText: "I see where you are coming from, but unit economics simply will not scale on that infrastructure.",
  },
  {
    id: "disc-dis-7",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "That might be true in theory, but in practice [clause]",
    authenticExampleEn: "Microservices sound elegant in theory, but in practice they compound operational friction.",
    pragmaticFunctionRu: "Деконструкция теоретического тезиса путем сопоставления с реальными ограничениями среды.",
    russianEquivalent: "В теории это может звучать верно, но на практике",
    slotType: "[clause]",
    slotSwaps: [
      "...sound elegant in theory, but in practice they compound operational and networking friction.",
      "...that might be true in theory, but in practice our client support team receives eighty tickets per day.",
      "...that might be true in theory, but in practice cross-departmental alignment takes weeks.",
      "...that might be true in theory, but in practice browser memory limits prevent clients from rendering that data.",
    ],
    audioText: "Microservices sound elegant in theory, but in practice they compound operational friction.",
  },
  {
    id: "disc-dis-8",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "I would not go so far as to say that [clause]",
    authenticExampleEn: "The rollout suffered minor setbacks, but I would not go so far as to say the sprint failed.",
    pragmaticFunctionRu: "Корректировка гиперболизации и возвращение дискурса к взвешенным объективным оценкам.",
    russianEquivalent: "Я бы не заходил так далеко, утверждая, что",
    slotType: "[clause]",
    slotSwaps: [
      "...but I would not go so far as to say that the entire sprint failed.",
      "...I would not go so far as to say that the legacy stack is fundamentally broken.",
      "...I would not go so far as to say that competitor solutions have made our offering obsolete.",
      "...I would not go so far as to say that the client relationship is permanently damaged.",
    ],
    audioText: "The rollout suffered minor setbacks, but I would not go so far as to say the sprint failed.",
  },
  {
    id: "disc-dis-9",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "The flaw in that argument is that [clause]",
    authenticExampleEn: "The flaw in that argument is that it treats consumer elasticity as completely invariant.",
    pragmaticFunctionRu: "Аналитическое указание на системную ошибку или неучтенный фактор в посылке оппонента.",
    russianEquivalent: "Слабое место этого довода состоит в том, что",
    slotType: "[clause]",
    slotSwaps: [
      "The flaw in that argument is that it treats consumer elasticity as completely invariant.",
      "The flaw in that argument is that it overlooks server egress costs during data re-synchronization.",
      "The flaw in that argument is that it assumes every enterprise user has administrative permissions.",
      "The flaw in that argument is that it ignores the compounding cognitive cost of context switching.",
    ],
    audioText: "The flaw in that argument is that it treats consumer elasticity as completely invariant.",
  },
  {
    id: "disc-dis-10",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "Don't get me wrong, but [clause]",
    authenticExampleEn: "Don't get me wrong, but we have to re-evaluate our commitment to that legacy stack.",
    pragmaticFunctionRu: "Предупреждение эмоционального или превратного истолкования жесткой критики.",
    russianEquivalent: "Поймите меня правильно, но",
    slotType: "[clause]",
    slotSwaps: [
      "Don't get me wrong, but we have to re-evaluate our commitment to that legacy stack.",
      "Don't get me wrong, but the current sprint velocity does not support four custom integrations.",
      "Don't get me wrong, but our enterprise contract requires stricter confidentiality safeguards.",
      "Don't get me wrong, but we cannot sacrifice latency benchmarks for aesthetic visual redesigns.",
    ],
    audioText: "Don't get me wrong, but we have to re-evaluate our commitment to that legacy stack.",
  },
  {
    id: "disc-dis-11",
    blockId: "disagreement",
    blockNameRu: "Прагматически смягченное несогласие",
    blockNumber: "03",
    frameEn: "I beg to differ on that point, simply because [clause]",
    authenticExampleEn: "I beg to differ on that point, simply because field diagnostics contradict that assumption.",
    pragmaticFunctionRu: "Маркер твердого несогласия, опирающегося на конкретные эмпирические данные.",
    russianEquivalent: "Позволю себе не согласиться по этому пункту, просто потому что",
    slotType: "[clause]",
    slotSwaps: [
      "I beg to differ on that point, simply because field diagnostics contradict that assumption.",
      "I beg to differ on that point, simply because customer retention logs show thirty percent quarterly churn.",
      "I beg to differ on that point, simply because our load tests crashed at twenty thousand concurrent queries.",
      "I beg to differ on that point, simply because legal compliance mandates audit log retention for seven years.",
    ],
    audioText: "I beg to differ on that point, simply because field diagnostics contradict that assumption.",
  },

  // BLOCK 4: Концессивные структуры: частичное согласие и стратегическая уступка (10 chunks)
  {
    id: "disc-con-1",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "That is a fair point, yet [clause]",
    authenticExampleEn: "That is a fair point, yet the regulatory deadlines prevent us from doing an overhaul.",
    pragmaticFunctionRu: "Признание обоснованности довода собеседника с немедленным смещением приоритета.",
    russianEquivalent: "Это справедливое замечание, и все же",
    slotType: "[clause]",
    slotSwaps: [
      "That is a fair point, yet the regulatory deadlines prevent us from undertaking a full overhaul.",
      "That is a fair point, yet our infrastructure budget is capped for this financial quarter.",
      "That is a fair point, yet user telemetry demonstrates strong loyalty to the existing workflow.",
      "That is a fair point, yet maintaining backwards compatibility remains our primary contractual duty.",
    ],
    audioText: "That is a fair point, yet the regulatory deadlines prevent us from doing an overhaul.",
  },
  {
    id: "disc-con-2",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "Having said that, [clause]",
    authenticExampleEn: "The feature improves engagement. Having said that, backend overhead grew unacceptably.",
    pragmaticFunctionRu: "Введение контрастирующего ограничительного фактора к ранее одобренному тезису.",
    russianEquivalent: "Сказав это / Вместе с тем",
    slotType: "[clause]",
    slotSwaps: [
      "...Having said that, backend overhead grew unacceptably after the rollout.",
      "Having said that, we cannot compromise database redundancy for the sake of premature delivery.",
      "Having said that, our customer support bandwidth is already strained to capacity.",
      "Having said that, the licensing terms impose significant limitations on commercial redistribution.",
    ],
    audioText: "The feature improves engagement. Having said that, backend overhead grew unacceptably.",
  },
  {
    id: "disc-con-3",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "Admittedly, [clause], but [clause]",
    authenticExampleEn: "Admittedly, upfront migration costs are high, but long-term savings justify the outlay.",
    pragmaticFunctionRu: "Добровольное признание недостатка собственной позиции для демонстрации ее общего превосходства.",
    russianEquivalent: "Надо признать, что [...], однако",
    slotType: "[clause]",
    slotSwaps: [
      "Admittedly, upfront migration costs are high, but long-term operational savings justify the outlay.",
      "Admittedly, the learning curve is steep, but the productivity gains become obvious within two weeks.",
      "Admittedly, initial telemetry showed latency spikes, but the caching layer has stabilized performance.",
      "Admittedly, our pricing tier is premium, but our round-the-clock enterprise SLA is unmatched in the industry.",
    ],
    audioText: "Admittedly, upfront migration costs are high, but long-term savings justify the outlay.",
  },
  {
    id: "disc-con-4",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "There is no denying that [clause], nonetheless [clause]",
    authenticExampleEn: "There is no denying that attrition has risen; nonetheless, foundational metrics remain stable.",
    pragmaticFunctionRu: "Фиксация неоспоримого негативного факта с удержанием общего конструктивного вывода.",
    russianEquivalent: "Нельзя отрицать, что [...], тем не менее",
    slotType: "[clause]",
    slotSwaps: [
      "There is no denying that attrition has risen; nonetheless, foundational engagement metrics remain stable.",
      "There is no denying that the initial beta had bugs; nonetheless, client enthusiasm remains exceptionally high.",
      "There is no denying that the deadline was aggressive; nonetheless, the core engine was delivered on budget.",
      "There is no denying that cloud expenses climbed; nonetheless, our gross margin expansion exceeds twenty percent.",
    ],
    audioText: "There is no denying that attrition has risen; nonetheless, foundational metrics remain stable.",
  },
  {
    id: "disc-con-5",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "I concede that [clause], but we must consider [noun]",
    authenticExampleEn: "I concede that delivery slipped, but we must consider the scope expansion requested by the client.",
    pragmaticFunctionRu: "Формальная тактическая уступка по частному вопросу с апелляцией к общему контексту.",
    russianEquivalent: "Я признаю, что [...], но мы обязаны учитывать",
    slotType: "[clause] / [noun]",
    slotSwaps: [
      "I concede that delivery slipped, but we must consider the scope expansion requested by the client.",
      "I concede that memory consumption increased, but we must consider the massive throughput increase.",
      "I concede that onboarding requires training, but we must consider the strict compliance environment of healthcare.",
      "I concede that our roadmap adjusted, but we must consider the macroeconomic volatility in the enterprise sector.",
    ],
    audioText: "I concede that delivery slipped, but we must consider the scope expansion requested by the client.",
  },
  {
    id: "disc-con-6",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "That makes a lot of sense, however [clause]",
    authenticExampleEn: "Expanding into regional markets makes a lot of sense, however cash flow is currently constrained.",
    pragmaticFunctionRu: "Валидация разумности идеи перед указанием на объективную невозможность ее текущей реализации.",
    russianEquivalent: "В этом много смысла, однако",
    slotType: "[clause]",
    slotSwaps: [
      "...makes a lot of sense, however our cash flow is currently constrained by Q4 debt obligations.",
      "That makes a lot of sense, however our backend engineers are dedicated to security hardening until November.",
      "That makes a lot of sense, however enterprise buyers rarely accept multi-tenant isolation architectures.",
      "That makes a lot of sense, however international patent filings take upwards of eight months.",
    ],
    audioText: "Expanding into regional markets makes a lot of sense, however cash flow is currently constrained.",
  },
  {
    id: "disc-con-7",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "I am with you on that, up to a certain point.",
    authenticExampleEn: "I am with you on that, up to a certain point, but abandoning code review is unacceptable.",
    pragmaticFunctionRu: "Фиксация предела согласия и предотвращение радикализации чужого предложения.",
    russianEquivalent: "Я согласен с вами в этом до определенных пределов",
    slotType: "[fixed / clause]",
    slotSwaps: [
      "I am with you on that, up to a certain point, but abandoning code review is completely unacceptable.",
      "I am with you on that, up to a certain point, but bypassing automated integration suites invites catastrophic outages.",
      "I am with you on that, up to a certain point, but discounting fifty percent erodes brand credibility.",
      "I am with you on that, up to a certain point, but we cannot compromise GDPR standards for convenience.",
    ],
    audioText: "I am with you on that, up to a certain point, but abandoning code review is unacceptable.",
  },
  {
    id: "disc-con-8",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "While I grant you that [clause], [clause]",
    authenticExampleEn: "While I grant you that costs climbed, developer throughput doubled over the same period.",
    pragmaticFunctionRu: "Дипломатическое признание факта оппонента в подчиненной синтагме с сильным главным тезисом.",
    russianEquivalent: "Притом что я признаю [...], фактически",
    slotType: "[clause]",
    slotSwaps: [
      "While I grant you that costs climbed, developer throughput doubled over the exact same period.",
      "While I grant you that initial feedback was mixed, net promoter scores surged in week four.",
      "While I grant you that setup requires effort, the automated recovery mechanism saves hundreds of hours annually.",
      "While I grant you that competitor pricing is lower, their uptime SLA does not meet financial service standards.",
    ],
    audioText: "While I grant you that costs climbed, developer throughput doubled over the same period.",
  },
  {
    id: "disc-con-9",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "Fair enough, but looking at it realistically, [clause]",
    authenticExampleEn: "Fair enough, but looking at it realistically, our current infrastructure cannot absorb the spike.",
    pragmaticFunctionRu: "Принятие рациональности позиции собеседника с проверкой на ресурсную осуществимость.",
    russianEquivalent: "Справедливо, но если взглянуть на вещи реалистично",
    slotType: "[clause]",
    slotSwaps: [
      "Fair enough, but looking at it realistically, our current infrastructure cannot absorb such traffic spikes.",
      "Fair enough, but looking at it realistically, we do not have sufficient engineering capacity for both tracks.",
      "Fair enough, but looking at it realistically, the enterprise sales cycle will require at least four months.",
      "Fair enough, but looking at it realistically, external auditors will demand proof of data segregation.",
    ],
    audioText: "Fair enough, but looking at it realistically, our current infrastructure cannot absorb the spike.",
  },
  {
    id: "disc-con-10",
    blockId: "concession",
    blockNameRu: "Концессивные структуры и уступка",
    blockNumber: "04",
    frameEn: "Even so, it remains true that [clause]",
    authenticExampleEn: "Defect rates dipped marginally. Even so, it remains true that test coverage is inadequate.",
    pragmaticFunctionRu: "Подтверждение фундаментального вывода вопреки отдельным единичным колебаниям.",
    russianEquivalent: "Даже с учетом этого фактом остается то, что",
    slotType: "[clause]",
    slotSwaps: [
      "...Even so, it remains true that our overall test coverage is completely inadequate.",
      "Even so, it remains true that customer churn correlates directly with system latency.",
      "Even so, it remains true that reliance on single-cloud architecture introduces severe catastrophic risk.",
      "Even so, it remains true that clear documentation is the primary predictor of successful onboarding.",
    ],
    audioText: "Defect rates dipped marginally. Even so, it remains true that test coverage is inadequate.",
  },

  // BLOCK 5: Когнитивное маневрирование и заполнение пауз обдумывания (10 chunks)
  {
    id: "disc-man-1",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "That is an interesting angle; let me think about that.",
    authenticExampleEn: "That is an interesting angle; let me think about that before committing to an architecture.",
    pragmaticFunctionRu: "Получение законной паузы в 2–3 секунды для осмысления сложного встречного вопроса без неловкости.",
    russianEquivalent: "Это интересный ракурс; позвольте мне обдумать это",
    slotType: "[fixed / clause]",
    slotSwaps: [
      "That is an interesting angle; let me think about that before committing to a specific database engine.",
      "That is an interesting angle; let me think about that in the context of our multi-region redundancy goals.",
      "That is an interesting angle; let me take a few seconds to evaluate the resource trade-offs.",
      "That is an interesting angle; let me think about that and circle back with hard metrics tomorrow.",
    ],
    audioText: "That is an interesting angle; let me think about that before committing to an architecture.",
  },
  {
    id: "disc-man-2",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "That is not something I have considered before, but [clause]",
    authenticExampleEn: "That is not something I have considered before, but initial estimates suggest feasibility.",
    pragmaticFunctionRu: "Демонстрация интеллектуальной честности и открытости новой информации с удержанием роли эксперта.",
    russianEquivalent: "Я не рассматривал это в таком ключе ранее, но",
    slotType: "[clause]",
    slotSwaps: [
      "That is not something I have considered before, but initial architectural estimates suggest feasibility.",
      "That is not something I have considered before, but the licensing implications warrant careful scrutiny.",
      "That is not something I have considered before, but our telemetry infrastructure could certainly adapt.",
      "That is not something I have considered before, but customer feedback strongly points in that direction.",
    ],
    audioText: "That is not something I have considered before, but initial estimates suggest feasibility.",
  },
  {
    id: "disc-man-3",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "The thing is, [clause]",
    authenticExampleEn: "The thing is, we cannot scale clusters without redesigning the persistence layer.",
    pragmaticFunctionRu: "Разговорный переход к корневому, часто невидимому или замалчиваемому препятствию.",
    russianEquivalent: "Дело в том, что",
    slotType: "[clause]",
    slotSwaps: [
      "The thing is, we cannot scale worker clusters without redesigning the persistence layer.",
      "The thing is, enterprise legal teams require at least three weeks for data processing agreements.",
      "The thing is, our current CI/CD pipeline does not support ephemeral staging environments.",
      "The thing is, our senior engineers are entirely committed to the SOC2 certification audit.",
    ],
    audioText: "The thing is, we cannot scale clusters without redesigning the persistence layer.",
  },
  {
    id: "disc-man-4",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "To tell you the truth, [clause]",
    authenticExampleEn: "To tell you the truth, internal audits have identified serious gaps in compliance.",
    pragmaticFunctionRu: "Создание доверительного профессионального регистра и маркирование откровенного высказывания.",
    russianEquivalent: "По правде говоря",
    slotType: "[clause]",
    slotSwaps: [
      "To tell you the truth, internal audits have identified serious gaps in regulatory compliance.",
      "To tell you the truth, our team was skeptical of the framework until we ran the synthetic load benchmarks.",
      "To tell you the truth, customer adoption has outpaced our most optimistic capacity models.",
      "To tell you the truth, we underestimated the migration overhead by at least thirty percent.",
    ],
    audioText: "To tell you the truth, internal audits have identified serious gaps in compliance.",
  },
  {
    id: "disc-man-5",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "For the most part, [clause]",
    authenticExampleEn: "For the most part, regional operations adapted smoothly to the new ERP protocol.",
    pragmaticFunctionRu: "Ограничение абсолютности утверждения; защита от обвинений в обобщении без фактов.",
    russianEquivalent: "По большей части",
    slotType: "[clause]",
    slotSwaps: [
      "For the most part, regional operations adapted smoothly to the new ERP protocol.",
      "For the most part, customer sentiment remains buoyant despite the recent subscription price adjustment.",
      "For the most part, the codebase adheres to strict type safety guidelines.",
      "For the most part, automated test flakiness has been isolated to legacy web socket suites.",
    ],
    audioText: "For the most part, regional operations adapted smoothly to the new ERP protocol.",
  },
  {
    id: "disc-man-6",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "As a matter of fact, [clause]",
    authenticExampleEn: "The forecast seemed grim, but as a matter of fact, subscription uptake surged in Q4.",
    pragmaticFunctionRu: "Введение уточняющего или опровергающего факта в противовес ожиданиям или сомнениям аудитории.",
    russianEquivalent: "Собственно говоря / На самом деле",
    slotType: "[clause]",
    slotSwaps: [
      "...but as a matter of fact, subscription uptake surged beyond twenty percent in Q4.",
      "As a matter of fact, the microservice architecture reduced inter-service latency across all clusters.",
      "As a matter of fact, two Fortune 500 prospects requested early access to the upcoming API.",
      "As a matter of fact, automated regression testing cut our deployment failures by eighty percent.",
    ],
    audioText: "The forecast seemed grim, but as a matter of fact, subscription uptake surged in Q4.",
  },
  {
    id: "disc-man-7",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "If I had to put my finger on it, [clause]",
    authenticExampleEn: "If I had to put my finger on it, the delivery friction stems from ambiguous specifications.",
    pragmaticFunctionRu: "Прецизионная локализация неочевидной проблемы в условиях дефицита полной информации.",
    russianEquivalent: "Если бы мне нужно было точно указать причину",
    slotType: "[clause]",
    slotSwaps: [
      "If I had to put my finger on it, the delivery friction stems from ambiguous feature specifications.",
      "If I had to put my finger on it, client hesitation is caused by uncertainty surrounding data ownership.",
      "If I had to put my finger on it, the root cause is poor cache invalidation logic during rolling updates.",
      "If I had to put my finger on it, team misalignment originated from conflicting KPI targets.",
    ],
    audioText: "If I had to put my finger on it, the delivery friction stems from ambiguous specifications.",
  },
  {
    id: "disc-man-8",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "How shall I put it... [clause]",
    authenticExampleEn: "The current team configuration is... how shall I put it... suboptimal for high-concurrency tasks.",
    pragmaticFunctionRu: "Взятие естественной паузы для подбора деликатной дипломатичной формулировки.",
    russianEquivalent: "Как бы это точнее выразить...",
    slotType: "[clause]",
    slotSwaps: [
      "The current team configuration is... how shall I put it... suboptimal for high-concurrency tasks.",
      "The vendor's commitment to our account has been... how shall I put it... noticeably inconsistent.",
      "The architectural documentation is... how shall I put it... somewhat lagging behind the production reality.",
      "Our current unit economics are... how shall I put it... reliant on favorable exchange rates.",
    ],
    audioText: "The current team configuration is... how shall I put it... suboptimal for high-concurrency tasks.",
  },
  {
    id: "disc-man-9",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "Well, it depends on how you look at it.",
    authenticExampleEn: "Well, it depends on how you look at it; higher churn might just mean low-value filters are working.",
    pragmaticFunctionRu: "Уход от плоской бинарной оценки ситуации и перевод дискуссии в многомерную плоскость.",
    russianEquivalent: "Смотря как на это посмотреть",
    slotType: "[fixed / clause]",
    slotSwaps: [
      "Well, it depends on how you look at it; higher churn might just mean low-value client filters are working.",
      "Well, it depends on how you look at it; slower velocity during refactoring builds compounding speed later.",
      "Well, it depends on how you look at it; strict compliance overhead protects our enterprise brand.",
      "Well, it depends on how you look at it; losing that deal saves us from disastrous custom obligations.",
    ],
    audioText: "Well, it depends on how you look at it; higher churn might just mean low-value filters are working.",
  },
  {
    id: "disc-man-10",
    blockId: "maneuvering",
    blockNameRu: "Когнитивное маневрирование и паузы",
    blockNumber: "05",
    frameEn: "Let's see; if we look at the core issue, [clause]",
    authenticExampleEn: "Let's see; if we look at the core issue, it is fundamentally a mismatch in technical priorities.",
    pragmaticFunctionRu: "Удержание дискурсивной инициативы с возвращением разговора к базовому предмету спора.",
    russianEquivalent: "Давайте посмотрим: если взглянуть на суть проблемы",
    slotType: "[clause]",
    slotSwaps: [
      "Let's see; if we look at the core issue, it is fundamentally a mismatch in technical priorities.",
      "Let's see; if we look at the core issue, customer churn is driven by onboarding latency, not product gaps.",
      "Let's see; if we look at the core issue, our infrastructure lacks automated horizontal autoscaling.",
      "Let's see; if we look at the core issue, the contract fails to specify penalties for unannounced API breakage.",
    ],
    audioText: "Let's see; if we look at the core issue, it is fundamentally a mismatch in technical priorities.",
  },

  // BLOCK 6: Метадискурсивное реформулирование, верификация и итоговый синтез (11 chunks)
  {
    id: "disc-syn-1",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "In other words, [clause]",
    authenticExampleEn: "In other words, the acquisition pipeline has effectively dried up over the past two quarters.",
    pragmaticFunctionRu: "Радикальное упрощение и кристаллизация комплексного многословного тезиса.",
    russianEquivalent: "Иными словами",
    slotType: "[clause]",
    slotSwaps: [
      "In other words, the acquisition pipeline has effectively dried up over the past two quarters.",
      "In other words, our backend architecture cannot support another ten thousand active web sockets.",
      "In other words, continuing with the current vendor will double our annual operating expenditure.",
      "In other words, shipping by Friday requires sacrificing the analytics dashboard module.",
    ],
    audioText: "In other words, the acquisition pipeline has effectively dried up over the past two quarters.",
  },
  {
    id: "disc-syn-2",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "What I am trying to get at is that [clause]",
    authenticExampleEn: "What I am trying to get at is that our unit economics do not support another funding round.",
    pragmaticFunctionRu: "Коррекция вектора высказывания во избежание смысловых искажений и двусмысленности.",
    russianEquivalent: "То, к чему я клоню, сводится к тому, что",
    slotType: "[clause]",
    slotSwaps: [
      "What I am trying to get at is that our unit economics do not support another speculative funding round.",
      "What I am trying to get at is that developer ergonomics directly dictate product shipping velocity.",
      "What I am trying to get at is that enterprise security reviews will stall without SOC2 attestation.",
      "What I am trying to get at is that our pricing model penalizes our most loyal enterprise accounts.",
    ],
    audioText: "What I am trying to get at is that our unit economics do not support another funding round.",
  },
  {
    id: "disc-syn-3",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "To put it another way, [clause]",
    authenticExampleEn: "To put it another way, the software solves a pain point that clients refuse to pay for.",
    pragmaticFunctionRu: "Переформулирование мысли с альтернативного понятийного или коммерческого ракурса.",
    russianEquivalent: "Иначе говоря / Если сформулировать это иначе",
    slotType: "[clause]",
    slotSwaps: [
      "To put it another way, the software solves a pain point that enterprise clients refuse to pay for.",
      "To put it another way, we are trading long-term architectural stability for artificial sprint velocity.",
      "To put it another way, automated canary deployments represent the cheapest form of insurance.",
      "To put it another way, our current marketing strategy acquires users that our product cannot retain.",
    ],
    audioText: "To put it another way, the software solves a pain point that clients refuse to pay for.",
  },
  {
    id: "disc-syn-4",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "That is to say, [clause]",
    authenticExampleEn: "We must decouple the architecture; that is to say, services must operate independently.",
    pragmaticFunctionRu: "Введение строгого операционального уточнения или институциональной дефиниции.",
    russianEquivalent: "То есть / А именно",
    slotType: "[clause]",
    slotSwaps: [
      "...that is to say, individual services must operate and fail independently without cascading.",
      "That is to say, no pull request reaches production without eighty percent test coverage.",
      "That is to say, customer data never leaves European borders under our sovereign cloud agreement.",
      "That is to say, our revenue model shifts entirely from transactional fees to annual subscriptions.",
    ],
    audioText: "We must decouple the architecture; that is to say, services must operate independently.",
  },
  {
    id: "disc-syn-5",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "So, if I understand you correctly, [clause]",
    authenticExampleEn: "So, if I understand you correctly, you are proposing a total freeze on enterprise deployments?",
    pragmaticFunctionRu: "Метакоммуникативная проверка правильности понимания логики собеседника перед ответом.",
    russianEquivalent: "Итак, если я правильно вас понимаю",
    slotType: "[clause]",
    slotSwaps: [
      "So, if I understand you correctly, you are proposing a total freeze on enterprise deployments?",
      "So, if I understand you correctly, our contract allows zero flexibility regarding the October launch date?",
      "So, if I understand you correctly, we are deprecating the v1 REST API ahead of scheduled migration?",
      "So, if I understand you correctly, the marketing committee approved the additional paid search budget?",
    ],
    audioText: "So, if I understand you correctly, you are proposing a total freeze on enterprise deployments?",
  },
  {
    id: "disc-syn-6",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "Correct me if I'm wrong, but are you saying that [clause]?",
    authenticExampleEn: "Correct me if I'm wrong, but are you saying that the alpha test yielded zero retention?",
    pragmaticFunctionRu: "Вежливое дипломатичное подталкивание оппонента к экспликации скрытых неприятных выводов.",
    russianEquivalent: "Поправьте меня, если я ошибаюсь, но вы утверждаете, что",
    slotType: "[clause]",
    slotSwaps: [
      "Correct me if I'm wrong, but are you saying that the alpha test yielded zero thirty-day retention?",
      "Correct me if I'm wrong, but are you saying that our disaster recovery replica has never been tested under load?",
      "Correct me if I'm wrong, but are you saying that the lead investor rejected our revised valuation?",
      "Correct me if I'm wrong, but are you saying that our SOC2 compliance audit was postponed again?",
    ],
    audioText: "Correct me if I'm wrong, but are you saying that the alpha test yielded zero retention?",
  },
  {
    id: "disc-syn-7",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "At the end of the day, [clause]",
    authenticExampleEn: "At the end of the day, market traction validates software far more decisively than architecture.",
    pragmaticFunctionRu: "Прагматическое сведение полиаспектной комплексной проблемы к главному практическому результату.",
    russianEquivalent: "В конечном счете",
    slotType: "[clause]",
    slotSwaps: [
      "At the end of the day, market traction validates software far more decisively than architecture.",
      "At the end of the day, enterprise customers care about reliability and security over flashy features.",
      "At the end of the day, our margins determine our runway, not our prospective valuations.",
      "At the end of the day, a documented system that works beats an elegant architecture on paper.",
    ],
    audioText: "At the end of the day, market traction validates software far more decisively than architecture.",
  },
  {
    id: "disc-syn-8",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "All in all, [clause]",
    authenticExampleEn: "All in all, the refactoring sprint met its goals despite ongoing resource shortages.",
    pragmaticFunctionRu: "Балансирующий синтез разнонаправленных результатов дискурсивного этапа.",
    russianEquivalent: "В общем и целом",
    slotType: "[clause]",
    slotSwaps: [
      "All in all, the refactoring sprint met its primary goals despite ongoing developer shortages.",
      "All in all, the platform withstood holiday traffic spikes with ninety-nine point nine percent uptime.",
      "All in all, customer feedback confirms that the simplified onboarding reduced time-to-first-value.",
      "All in all, the transition to asynchronous operations has eliminated cross-time-zone communication bottlenecks.",
    ],
    audioText: "All in all, the refactoring sprint met its goals despite ongoing resource shortages.",
  },
  {
    id: "disc-syn-9",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "What it boils down to is that [clause]",
    authenticExampleEn: "What it boils down to is that we must defend our gross margins before committing to expansion.",
    pragmaticFunctionRu: "Редукция затянувшейся дискуссии до одного определяющего фундаментального фактора.",
    russianEquivalent: "Все сводится к тому, что",
    slotType: "[clause]",
    slotSwaps: [
      "What it boils down to is that we must defend our gross margins before committing to international expansion.",
      "What it boils down to is that our platform requires automated end-to-end regression guarantees.",
      "What it boils down to is that the client demands a legally binding SLA before signing.",
      "What it boils down to is that our current tech stack cannot sustain another doubling of concurrency.",
    ],
    audioText: "What it boils down to is that we must defend our gross margins before committing to expansion.",
  },
  {
    id: "disc-syn-10",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "Taking everything into consideration, [clause]",
    authenticExampleEn: "Taking everything into consideration, freezing capital expenditure is the safest corporate posture.",
    pragmaticFunctionRu: "Аналитическое резюмирование на базе всестороннего учета всех озвученных аргументов.",
    russianEquivalent: "Принимая во внимание все обстоятельства",
    slotType: "[clause]",
    slotSwaps: [
      "Taking everything into consideration, freezing speculative capital expenditure is the safest corporate posture.",
      "Taking everything into consideration, migrating to managed services will reduce total cost of ownership.",
      "Taking everything into consideration, promoting internal talent will preserve team culture and knowledge.",
      "Taking everything into consideration, launching a paid pilot mitigates financial risk for both parties.",
    ],
    audioText: "Taking everything into consideration, freezing capital expenditure is the safest corporate posture.",
  },
  {
    id: "disc-syn-11",
    blockId: "synthesis",
    blockNameRu: "Метадискурсивный синтез и резюме",
    blockNumber: "06",
    frameEn: "To wrap things up, [clause]",
    authenticExampleEn: "To wrap things up, our immediate developmental priority must remain system observability.",
    pragmaticFunctionRu: "Фиксация финальной смысловой границы и завершение аргументативного раунда переговоров.",
    russianEquivalent: "Подводя итог сказанному",
    slotType: "[clause]",
    slotSwaps: [
      "To wrap things up, our immediate developmental priority must remain end-to-end system observability.",
      "To wrap things up, we have aligned on the Q4 release roadmap and assigned explicit sprint ownership.",
      "To wrap things up, the vendor agreed to honor our custom uptime terms without price adjustments.",
      "To wrap things up, we will deliver the revised technical proposal by Thursday afternoon.",
    ],
    audioText: "To wrap things up, our immediate developmental priority must remain system observability.",
  },
] as const;

export const COMPARATIVE_REGISTERS: readonly ComparativeRegisterItem[] = [
  {
    id: "reg-1",
    functionRu: "Презентация собственного суждения",
    basicTemplateB1B2: "I think that... / In my opinion...",
    advancedFrameC1: "The way I see it... / I would argue that...",
    socioPragmaticEffectRu: "Переход от декларации субъективного частного мнения к формулированию взвешенного аналитического тезиса.",
    basicExample: "I think our software is too slow for big clients.",
    advancedExample: "The way I see it, our current database throughput falls short of enterprise SLA requirements.",
  },
  {
    id: "reg-2",
    functionRu: "Добавление доказательства",
    basicTemplateB1B2: "Also... / And... / Besides...",
    advancedFrameC1: "On top of that... / What is more...",
    socioPragmaticEffectRu: "Формирование драматургии аргументации и ранжирование доводов по возрастающей степени значимости.",
    basicExample: "Also, the server crashed yesterday, and customers are angry.",
    advancedExample: "On top of that, the database replica failed to achieve read consensus, compounding customer churn.",
  },
  {
    id: "reg-3",
    functionRu: "Введение контраста",
    basicTemplateB1B2: "But... / However...",
    advancedFrameC1: "That said... / Having said that...",
    socioPragmaticEffectRu: "Создание плавного интонационного перехода без фрагментации синтаксического потока речи.",
    basicExample: "The feature is good. But it is very expensive to maintain.",
    advancedExample: "The feature improves engagement. Having said that, backend overhead grew unacceptably.",
  },
  {
    id: "reg-4",
    functionRu: "Экспликация несогласия",
    basicTemplateB1B2: "I don't agree with you.",
    advancedFrameC1: "I take a slightly different view on... / I am not entirely convinced that...",
    socioPragmaticEffectRu: "Деэскалация когнитивного конфликта и сохранение партнерства по модели Face-Saving Acts.",
    basicExample: "I don't agree with you about hiring more developers.",
    advancedExample: "I take a slightly different view on engineering headcount; our primary bottleneck is architectural debt.",
  },
  {
    id: "reg-5",
    functionRu: "Аргументативная уступка",
    basicTemplateB1B2: "Yes, but...",
    advancedFrameC1: "Admittedly, [...] but we must consider...",
    socioPragmaticEffectRu: "Стратегическая валидация части аргументов оппонента для укрепления итоговой позиции.",
    basicExample: "Yes, but we have no money for this project.",
    advancedExample: "Admittedly, upfront migration costs are high, but long-term operational savings justify the outlay.",
  },
  {
    id: "reg-6",
    functionRu: "Заполнение когнитивной паузы",
    basicTemplateB1B2: "Элементарные паузы зависания (uhm, err, well)",
    advancedFrameC1: "That's an interesting angle; let me think about that...",
    socioPragmaticEffectRu: "Удержание контроля над коммуникативным каналом и поддержание акустической беглости речи.",
    basicExample: "Uhm... err... wait, I need to remember the rule...",
    advancedExample: "That is an interesting angle; let me think about that before committing to an architecture.",
  },
  {
    id: "reg-7",
    functionRu: "Синтетическое резюме",
    basicTemplateB1B2: "Finally... / In conclusion...",
    advancedFrameC1: "What it boils down to is that... / At the end of the day...",
    socioPragmaticEffectRu: "Концентрация внимания аудитории на сущностном системном выводе без школьной шаблонности.",
    basicExample: "In conclusion, we need to stop spending money.",
    advancedExample: "What it boils down to is that we must defend our gross margins before committing to international expansion.",
  },
] as const;

export const METHODOLOGY_STAGES: readonly MethodologyStageItem[] = [
  {
    id: "stage-1",
    number: "01",
    titleRu: "Слуховое моделирование и просодическая интеграция",
    subtitleRu: "Shadowing за носителями и фонологическая петля",
    descriptionRu:
      "Преодоление сегментного восприятия фраз. Автоматизация каркаса как единого неделимого фонетического слова с редукцией безударных служебных элементов и межсловным связыванием (linking).",
    keyProtocol: "Акустическое теневое повторение (Shadowing) x 10 повторений без подглядывания в текст",
    actionItem: "Добейтесь воспроизведения предикативного каркаса на одном дыхании за 400–600 мс.",
  },
  {
    id: "stage-2",
    number: "02",
    titleRu: "Вариативная субституция незамкнутых слотов",
    subtitleRu: "Скоростная подстановка семантических переменных",
    descriptionRu:
      "Разрушение жесткой связки каркаса с узким контекстом. Фиксированный каркас удерживается в моторной памяти, пока мозг на высокой скорости подключает к нему новые существительные и герундии.",
    keyProtocol: "Speed Substitution: 4 разных слота за 20 секунд к одному якорному основанию",
    actionItem: "Используйте встроенный тренажер Speed-Swapper для мгновенной подстановки вариантов.",
  },
  {
    id: "stage-3",
    number: "03",
    titleRu: "Метод прогрессивной компрессии временных интервалов",
    subtitleRu: "Протокол 4-3-2 под нарастающим дефицитом времени",
    descriptionRu:
      "Изложение тезиса с включением минимум 5 каркасов за 4 минуты, затем за 3 минуты, затем за 2 минуты. Жесткий лимит времени вынуждает мозг отсекать словесный шум и опираться на готовые формульные мосты.",
    keyProtocol: "Протокол 4-3-2: 4 мин → 3 мин → 2 мин с обязательным включением целевых каркасов",
    actionItem: "Увеличивает среднюю длину отрезка речи между паузами (MLR) в 2.4 раза.",
  },
  {
    id: "stage-4",
    number: "04",
    titleRu: "Контекстуализированное интервальное извлечение",
    subtitleRu: "Карточки по коммуникативно-кризисному триггеру",
    descriptionRu:
      "Отказ от прямого перевода изолированных слов. Стимулом на лицевой стороне карточки является прагматический кризис: 'Необходимо вежливо оспорить категоричный довод коллеги'.",
    keyProtocol: "Триггер кризиса на лицевой стороне → Формульный каркас на обороте",
    actionItem: "Вырабатывает мгновенный рефлекс извлечения каркаса под давлением на живом созвоне.",
  },
] as const;
