import { TenseChunkItem } from "./types";

export const TENSE_CHUNKS_DATA: readonly TenseChunkItem[] = [
  // ==========================================
  // Блок 1: Present Perfect (Жизненный опыт и свежие события)
  // ==========================================
  {
    id: "tense-1",
    number: "ЧАНК #1",
    block: "Блок 1 • Чанки 1–4",
    tenseName: "Present Perfect (Свежие результаты)",
    title: "I've already [past participle] [X]",
    trans: "«Я уже сделал [что-то]»",
    exEn: "I've already called the restaurant and reserved our table.",
    exRu: "Я уже набрал в ресторан и забронировал наш столик.",
    tip: "Используется, когда действие только что завершилось и результат актуален прямо сейчас.",
  },
  {
    id: "tense-2",
    number: "ЧАНК #2",
    block: "Блок 1 • Чанки 1–4",
    tenseName: "Present Perfect (Вопрос о статусе)",
    title: "Have you had a chance to [verb] yet?",
    trans: "«У тебя уже была возможность сделать [X]?»",
    exEn: "Have you had a chance to check out that new coffee shop yet?",
    exRu: "Ты уже успел заглянуть в ту новую кофейню?",
    tip: "Идеально мягкий вопрос вместо грубого «Did you do it?»",
  },
  {
    id: "tense-3",
    number: "ЧАНК #3",
    block: "Блок 1 • Чанки 1–4",
    tenseName: "Present Perfect (Неожиданные трудности)",
    title: "We've run into an issue with [X]",
    trans: "«Мы столкнулись со сложностью / проблемой в [X]»",
    exEn: "We've run into an issue with the flight booking, so we might need another date.",
    exRu: "У нас возникла заминка с бронью билетов, так что, возможно, выберем другую дату.",
    tip: "Спокойное сообщение о проблеме без паники.",
  },
  {
    id: "tense-4",
    number: "ЧАНК #4",
    block: "Блок 1 • Чанки 1–4",
    tenseName: "Present Perfect (Отсутствие результата)",
    title: "I haven't seen [X] yet",
    trans: "«Я пока еще не видел [X]»",
    exEn: "I haven't seen your latest message yet, let me check my phone.",
    exRu: "Я еще не видел твое последнее сообщение, дай гляну в телефон.",
    tip: "Естественный ответ, когда вас спрашивают о том, что вы еще не успели посмотреть.",
  },

  // ==========================================
  // Блок 2: Present Perfect Continuous (Продолжительность)
  // ==========================================
  {
    id: "tense-5",
    number: "ЧАНК #5",
    block: "Блок 2 • Чанки 5–7",
    tenseName: "Present Perfect Continuous (Усталость и фокус)",
    title: "I've been working on [X] all morning",
    trans: "«Я все утро занимаюсь [X]»",
    exEn: "I've been cleaning the garage all morning, and I'm totally exhausted.",
    exRu: "Я все утро разбирал гараж и буквально валюсь с ног.",
    tip: "Объясняет ваше текущее состояние через длительное действие.",
  },
  {
    id: "tense-6",
    number: "ЧАНК #6",
    block: "Блок 2 • Чанки 5–7",
    tenseName: "Present Perfect Continuous (Тянущаяся проблема)",
    title: "We've been dealing with [X] since [time]",
    trans: "«Мы мучаемся с этой ситуацией еще с [такого-то времени]»",
    exEn: "We've been dealing with this water leak since last Thursday.",
    exRu: "Мы воюем с этой протечкой труб еще с прошлого четверга.",
    tip: "Подчеркивает непрерывность проблемы и то, сколько сил она отнимает.",
  },
  {
    id: "tense-7",
    number: "ЧАНК #7",
    block: "Блок 2 • Чанки 5–7",
    tenseName: "Present Perfect Continuous (Вопрос о длительности)",
    title: "How long have you been [verb-ing]?",
    trans: "«Как давно ты этим занимаешься / ждешь?»",
    exEn: "How long have you been waiting out here in the cold?",
    exRu: "Как давно ты уже стоишь тут на таком холоде?",
    tip: "Самый живой способ спросить о длительности ожидания или процесса.",
  },

  // ==========================================
  // Блок 3: Past Continuous (Фон и прерывание)
  // ==========================================
  {
    id: "tense-8",
    number: "ЧАНК #8",
    block: "Блок 3 • Чанки 8–10",
    tenseName: "Past Continuous (Прерванное действие)",
    title: "I was in the middle of [verb-ing] when [X] happened",
    trans: "«Я был прямо посреди процесса [X], когда произошло [Y]»",
    exEn: "I was in the middle of cooking dinner when the power suddenly went out.",
    exRu: "Я был в самом разгаре готовки ужина, когда внезапно отключили свет.",
    tip: "Идеально объясняет внезапное прерывание вашего занятия.",
  },
  {
    id: "tense-9",
    number: "ЧАНК #9",
    block: "Блок 3 • Чанки 8–10",
    tenseName: "Past Continuous (В шаге от действия)",
    title: "I was just about to [verb] when...",
    trans: "«Я как раз собирался [сделать X], когда...»",
    exEn: "I was just about to call you when your text popped up!",
    exRu: "Я как раз собирался тебе набрать, и тут всплыло твое сообщение!",
    tip: "Удивительное совпадение или оправдание, почему вы не успели.",
  },
  {
    id: "tense-10",
    number: "ЧАНК #10",
    block: "Блок 3 • Чанки 8–10",
    tenseName: "Past Continuous (Фоновое обсуждение)",
    title: "We were looking into [X], but...",
    trans: "«Мы как раз присматривались к [X], но...»",
    exEn: "We were looking into buying a used car, but the prices are crazy right now.",
    exRu: "Мы как раз присматривались к покупке подержанной машины, но цены сейчас безумные.",
    tip: "Объяснение, почему идея отпала в процессе изучения.",
  },

  // ==========================================
  // Блок 4: Future & Spontaneous Plans (Планы и обязательства)
  // ==========================================
  {
    id: "tense-11",
    number: "ЧАНК #11",
    block: "Блок 4 • Чанки 11–13",
    tenseName: "Future & Spontaneous Plans",
    title: "We're on track to [verb] by [time]",
    trans: "«Мы успеваем сделать [X] к [такому-то времени]»",
    exEn: "We're completely on track to move into the new house by Friday.",
    exRu: "Мы полностью укладываемся в график, чтобы заехать в новый дом к пятнице.",
    tip: "Уверенность в соблюдении сроков без лишних слов.",
  },
  {
    id: "tense-12",
    number: "ЧАНК #12",
    block: "Блок 4 • Чанки 11–13",
    tenseName: "Future & Spontaneous Plans",
    title: "We're planning on [verb-ing]...",
    trans: "«Мы планируем / собираемся [делать X]...»",
    exEn: "We're planning on taking a road trip along the coast next weekend.",
    exRu: "Мы планируем махнуть на машине вдоль побережья на следующих выходных.",
    tip: "Самый живой разговорный оборот для озвучивания планов.",
  },
  {
    id: "tense-13",
    number: "ЧАНК #13",
    block: "Блок 4 • Чанки 11–13",
    tenseName: "Future & Spontaneous Plans",
    title: "I'll make sure to [verb]...",
    trans: "«Я обязательно прослежу за тем, чтобы [X]...»",
    exEn: "Don't worry, I'll make sure to lock both doors before going to bed.",
    exRu: "Не переживай, я обязательно запру обе двери перед сном.",
    tip: "Взятие личной ответственности за результат.",
  },

  // ==========================================
  // Блок 5: Conditionals & Diplomacy (Условия и гипотезы)
  // ==========================================
  {
    id: "tense-14",
    number: "ЧАНК #14",
    block: "Блок 5 • Чанки 14–17",
    tenseName: "Second Conditional (Мягкая просьба)",
    title: "It would be great if you could [verb]...",
    trans: "«Было бы здорово, если бы ты смог [X]...»",
    exEn: "It would be great if you could send over those photos when you get a chance.",
    exRu: "Было бы здорово, если бы ты скинул те фотки, как появится свободная минутка.",
    tip: "Ультимативный вежливый шаблон просьбы у носителей.",
  },
  {
    id: "tense-15",
    number: "ЧАНК #15",
    block: "Блок 5 • Чанки 14–17",
    tenseName: "Second Conditional (Дружеский совет)",
    title: "If I were you, I would just [verb]...",
    trans: "«На твоем месте я бы просто [X]...»",
    exEn: "If I were you, I would just tell them the truth right away.",
    exRu: "На твоем месте я бы просто сразу сказал им всю правду.",
    tip: "Мягкий совет без позиции наставника.",
  },
  {
    id: "tense-16",
    number: "ЧАНК #16",
    block: "Блок 5 • Чанки 14–17",
    tenseName: "Third Conditional (Сожаление о прошлом)",
    title: "We should have [past participle] earlier...",
    trans: "«Нам следовало сделать это пораньше...»",
    exEn: "We should have booked the hotel a few weeks earlier, prices doubled!",
    exRu: "Нам следовало забронировать отель на пару недель раньше — цены взлетели вдвое!",
    tip: "Осознание упущенной возможности.",
  },
  {
    id: "tense-17",
    number: "ЧАНК #17",
    block: "Блок 5 • Чанки 14–17",
    tenseName: "Third Conditional (Альтернативный исход)",
    title: "If we had known about this, we would have [past participle]...",
    trans: "«Если бы мы знали об этом, мы бы поступили иначе...»",
    exEn: "If we had known about the road closure, we would have taken the detour.",
    exRu: "Если бы мы знали о перекрытии дороги, мы бы поехали в объезд.",
    tip: "Формула объяснения прошлых решений без чувства вины.",
  },
] as const;
