import { LongreadItem } from "./types";

export const LONGREADS: readonly LongreadItem[] = [
  {
    id: "native-brain",
    slug: "native-brain",
    href: "/longreads/native-brain",
    title: "Мозг Носителя и Нейробиология Перехода на C1: Предиктивное Кодирование, Подавление L1 и Процедурная Беглость",
    shortTitle: "Мозг Носителя и Нейробиология C1",
    subtitle: "Как мозг носителя формирует речь без обдумывания грамматики, почему перевод с русского создает задержку в 800 мс и как перенести язык в базальные ганглии.",
    description: "Исследования fMRI, ERP-потенциалы N400/P600, модель свободного вычисления Карла Фристона, двухпотоковая модель Хикока-Поппеля и подавление интерференции L1.",
    category: "neuroscience",
    categoryLabel: "Нейробиология",
    readTime: "17 мин",
    badge: "Исследование 🧠",
    badgeColor: "cyan",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "Karl Friston (Predictive Processing)",
      "Hickok & Poeppel (Dual-Stream Model)",
      "Michael Ullman (Declarative/Procedural)",
      "David Green (Inhibitory Control)",
    ],
    toc: [
      { id: "chapter-1", title: "01. Концептуальный разрыв: Компьютерная модель vs Предиктивный мозг" },
      { id: "chapter-2", title: "02. Хронометрия речи и потенциалы N400 / P600" },
      { id: "chapter-3", title: "03. Двухпотоковая модель: Вентральный vs Дорсальный путь" },
      { id: "chapter-4", title: "04. Декларативно-процедурная модель Майкла Ульмана" },
      { id: "chapter-5", title: "05. Модель ингибиторного контроля и цена подавления L1 (Switching Cost)" },
      { id: "chapter-6", title: "06. Практический нейропротокол перестройки контуров на уровень C1" },
    ],
    featured: true,
  },
  {
    id: "memory-consolidation",
    slug: "memory-consolidation",
    href: "/longreads/memory-consolidation",
    title: "Наука Консолидации Памяти: Долговременная Потенциация (LTP), Фазы Сна, Эффект Тестирования и Желательные Трудности",
    shortTitle: "Наука Памяти и Консолидации",
    subtitle: "Молекулярные механизмы закрепления языка: закон Хебба, гиппокамп против неокортекса, сонные рипплы во сне со скоростью x20 и алгоритмы интервального повторения.",
    description: "Разбор того, почему перечитывание конспектов создает ложную иллюзию беглости, как активное извлечение запускает реконсолидацию синапсов и как использовать интерливинг.",
    category: "memory",
    categoryLabel: "Память и Обучение",
    readTime: "16 мин",
    badge: "Исследование 🧬",
    badgeColor: "emerald",
    targetLevel: "Все уровни (SLA)",
    scientificPillars: [
      "Bliss & Lømo (Long-Term Potentiation)",
      "McClelland (Complementary Learning Systems)",
      "Roediger & Karpicke (Testing Effect)",
      "Robert Bjork (Desirable Difficulties)",
      "Jan Born & Matthew Walker (Sleep Consolidation)",
    ],
    toc: [
      { id: "part-1", title: "01. Молекулярный фундамент памяти: Закон Хебба и каскад LTP" },
      { id: "part-2", title: "02. Комплементарные системы обучения: Гиппокамп и Неокортекс" },
      { id: "part-3", title: "03. Сон: Медленноволновые волны-рипплы и семантическая интеграция REM" },
      { id: "part-4", title: "04. Эффект тестирования: Почему пассивное чтение бесполезно" },
      { id: "part-5", title: "05. Желательные трудности Бьорка и сила интерливинга" },
      { id: "part-6", title: "06. Математика забывания: От Эббингауза к современному FSRS" },
    ],
    featured: true,
  },
  {
    id: "chunk-architecture",
    slug: "chunk-architecture",
    href: "/longreads/chunk-architecture",
    title: "Архитектура Памяти на Чанках: Как Мозг Кодирует, Сжимает и Мгновенно Извлекает Речевые Блоки",
    shortTitle: "Архитектура Чанков в Памяти",
    subtitle: "Лимиты рабочей памяти (4±1 слота по Ковану), шахматные гроссмейстеры и лингвистика, моторный чанкинг базальных ганглиев и архитектура Frame-and-Slot.",
    description: "Фундаментальный разбор того, как мозг упаковывает синтаксические деревья в атомарные ментальные токены, экономя до 75% когнитивного ресурса для свободной спонтанной речи.",
    category: "chunks",
    categoryLabel: "Речевые Чанки",
    readTime: "15 мин",
    badge: "Исследование 🧩",
    badgeColor: "indigo",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "Nelson Cowan (Working Memory 4±1)",
      "Chase & Simon (Cognitive Chunking)",
      "Ann Graybiel (Basal Ganglia Motor Chunking)",
      "Gordon Logan (Instance Theory)",
      "Alison Wray (Formulaic Language & Lexicon)",
    ],
    toc: [
      { id: "sec-1", title: "01. Закон рабочей памяти: 4±1 слота по Нельсону Ковану" },
      { id: "sec-2", title: "02. Когнитивный чанкинг: От шахматных гроссмейстеров к речи" },
      { id: "sec-3", title: "03. Базальные ганглии: Start/Stop нейроны и моторное сжатие" },
      { id: "sec-4", title: "04. Теория экземпляров Логана vs Алгоритмический синтаксис" },
      { id: "sec-5", title: "05. Когнитивная архитектура «Frame-and-Slot» в живой речи" },
      { id: "sec-6", title: "06. 4-шаговый алгоритм создания несгораемых речевых чанков" },
    ],
    featured: true,
  },
  {
    id: "fluency-guide",
    slug: "fluency-guide",
    href: "/fluency-guide",
    title: "Архитектура Беглости B2 → C1: Как Перестать Мычать и Начать Говорить",
    shortTitle: "Архитектура Беглости B2 → C1",
    subtitle: "Преодоление речевого затыка, серкумлокуция (мгновенное описание забытых слов), дискурсивные мосты и спонтанные ответы по фреймворку PREP.",
    description: "Разбор ментального лексикона, психологии страха тишины, устранения звуков «эээ/ммм» и 25-минутного протокола осознанной практики для рабочих созвонов.",
    category: "neuroscience",
    categoryLabel: "Беглость и Речь",
    readTime: "18 мин",
    badge: "Беглость ⚡",
    badgeColor: "emerald",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "Michael Lewis (The Lexical Approach)",
      "Stephen Krashen (The Monitor Hypothesis)",
      "Paul Nation (Speech Fluency Development)",
    ],
    toc: [
      { id: "chapter-1", title: "01. Парадокс уровня B2: Почему вы всё понимаете, но зависаете на созвонах" },
      { id: "chapter-2", title: "02. Серкумлокуция: Механика мгновенного описания любого забытого слова" },
      { id: "chapter-3", title: "03. Ликвидация «Эээ»: Сила немой паузы, замок губ и 25 дискурсивных мостов" },
      { id: "chapter-4", title: "04. Деловая речь: Фреймворк PREP для спонтанных ответов и C1 Hedging" },
      { id: "chapter-5", title: "05. Ежедневный протокол тренировок: Что конкретно делать каждый день" },
      { id: "chapter-6", title: "06. Промпты для AI-спарринга и 30-дневный пошаговый план" },
    ],
  },
  {
    id: "chunks",
    slug: "chunks",
    href: "/chunks",
    title: "Лексические Чанки: Как Мозг Носителей Говорит Блоками без Зависаний",
    shortTitle: "Фундамент Лексических Чанков",
    subtitle: "Когнитивная механика блочной речи. Почему попытка строить фразы по одному слову гарантирует затыки и как разгрузить оперативную память мозга в 4 раза.",
    description: "4 вида чанков (коллокации, фиксированные фразы, полуфиксированные рамки со слотами, дискурсивные маркеры), база 30 ключевых рабочих блоков и методика усвоения.",
    category: "chunks",
    categoryLabel: "Речевые Чанки",
    readTime: "14 мин",
    badge: "Фундамент 🧱",
    badgeColor: "cyan",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "Michael Lewis (The Lexical Approach)",
      "Pawley & Syder (Two Puzzles for Linguistic Theory)",
      "George Miller (Working Memory)",
    ],
    toc: [
      { id: "chunk-1", title: "01. Что такое лексический чанк и главный парадокс беглости" },
      { id: "chunk-2", title: "02. Нейробиология: Закон рабочей памяти Миллера и Кована" },
      { id: "chunk-3", title: "03. 4 вида чанков: От коллокаций до полуфиксированных рамок" },
      { id: "chunk-4", title: "04. Книжный английский против Живой речи на созвонах" },
      { id: "chunk-5", title: "05. Пошаговая методика: Как находить, учить и внедрять чанки" },
      { id: "chunk-6", title: "06. База 30 самых нужных рабочих чанков (без духоты)" },
    ],
  },
  {
    id: "dense-structure",
    slug: "dense-structure",
    href: "/dense-structure",
    title: "Плотные Структурные Чанки: 3 Уровня Сочленений и Связок",
    shortTitle: "Плотные Структурные Чанки",
    subtitle: "От базовых рабочих оправданий до тонкой дипломатии и естественных связующих оборотов. Исследования Alison Wray и Douglas Biber.",
    description: "Анатомия сложных глагольных сочленений («haven't gotten around to», «was supposed to»), где мозг чаще всего спотыкается, и трехуровневая матрица внедрения.",
    category: "chunks",
    categoryLabel: "Речевые Чанки",
    readTime: "14 мин",
    badge: "Связность 🔗",
    badgeColor: "violet",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "Alison Wray (Formulaic Language)",
      "Douglas Biber (Lexical Bundles in Speech)",
      "Norbert Schmitt (Formulaic Sequences)",
    ],
    toc: [
      { id: "part-1", title: "01. Научные исследования: Холистическая обработка против синтаксиса" },
      { id: "part-2", title: "02. Анатомия сложности: Почему русскоязычный мозг спотыкается на этих фразах" },
      { id: "part-3", title: "03. Уровень 1: Фундамент действий и результатов (Стендапы и задачи)" },
      { id: "part-4", title: "04. Уровень 2: Процессы, привычки и объяснения задержек" },
      { id: "part-5", title: "05. Уровень 3: Дипломатия, сожаления и гипотезы C1" },
      { id: "part-6", title: "06. Метод тренировки Slot-Pacing (Артикуляция на одном выдохе)" },
    ],
  },
  {
    id: "tense-chunks",
    slug: "tense-chunks",
    href: "/tense-chunks",
    title: "Времена Plug & Play: 24 Шаблона от 1 до 24 Без Формул",
    shortTitle: "Времена Plug & Play",
    subtitle: "Времена без школьных таблиц: готовые речевые блоки для настоящего, прошедшего и будущего с исследованиями Joan Bybee и Nick Ellis.",
    description: "24 готовых временных шаблона с жестким каркасом и свободным слотом под глагол. Метод Speed Swapping для автоматизации Present Perfect, Continuous и Conditionals.",
    category: "chunks",
    categoryLabel: "Грамматика и Времена",
    readTime: "10 мин",
    badge: "Времена ⏱️",
    badgeColor: "indigo",
    targetLevel: "A2 → C1",
    scientificPillars: [
      "Joan Bybee (Exemplar Theory of Aspect)",
      "Nick C. Ellis (Implicit Second Language Acquisition)",
    ],
    toc: [
      { id: "tense-1", title: "01. Научные исследования: Почему таблицы времен убивают спонтанную речь" },
      { id: "tense-2", title: "02. Принцип Plug & Play: Жесткая голова и свободный слот" },
      { id: "tense-3", title: "03. Блок 1 (#1–#4): Present Perfect (Результат к этой минуте)" },
      { id: "tense-4", title: "04. Блок 2 (#5–#7): Present Perfect Continuous (Длительный процесс)" },
      { id: "tense-5", title: "05. Блок 3 (#8–#10): Past Continuous (Фон и прерывание)" },
      { id: "tense-6", title: "06. Блок 4 (#11–#12): Обязательства и срывы планов" },
      { id: "tense-7", title: "07. Метод тренировки Speed Swapping" },
    ],
  },
  {
    id: "methodology",
    slug: "methodology",
    href: "/methodology",
    title: "Научные Методологии Изучения: Аудит Рутины, 4 Потока и Беглость",
    shortTitle: "Методология Обучения SLA",
    subtitle: "Когнитивный аудит шэдоуинга, 4 потока Пола Нейшна, устранение барьера аутпута и 3 готовых тайм-плана дейли-рутины (20 / 35 / 50 минут).",
    description: "Разбор того, почему повторения за диктором недостаточно для спонтанной речи, что такое Production Gap и как выстроить ежедневную систему осознанной практики.",
    category: "methodology",
    categoryLabel: "Методология",
    readTime: "14 мин",
    badge: "Система 📐",
    badgeColor: "amber",
    targetLevel: "Все уровни (SLA)",
    scientificPillars: [
      "Paul Nation (The Four Strands)",
      "Merrill Swain (Output Hypothesis)",
      "Richard Schmidt (Noticing Hypothesis)",
      "K. Anders Ericsson (Deliberate Practice)",
    ],
    toc: [
      { id: "part-1", title: "01. Аудит вашей текущей рутины: Сильные стороны и слепые зоны" },
      { id: "part-2", title: "02. Фундаментальные научные теории SLA (Nation, Swain, Schmidt, Ericsson)" },
      { id: "part-3", title: "03. 5 недостающих элементов: Что внедрить в ежедневную практику" },
      { id: "part-4", title: "04. Три готовых сценария идеальной дейли-рутины (Sprint, Standard, Immersion)" },
      { id: "part-5", title: "05. Ежедневный чек-лист эффективности и объективные метрики прогресса" },
    ],
  },
  {
    id: "audit-chunks",
    slug: "audit-chunks",
    href: "/audit-chunks",
    title: "Персональный Чанк-Аудит: Антидоты к 7 Фоссилизированным Калькам",
    shortTitle: "Чанки из Аудита 🎯",
    subtitle: "Практический интерактивный каталог чанков-антидотов, устраняющих ключевые русскоязычные интерференции и грамматические пробелы из диагностического теста.",
    description: "Интерактивная тренировка 7 персональных кластеров: зависимые предлоги, исчисляемость, Conditionals, модальные прошедшие формы и кальки русского порядка слов.",
    category: "audit",
    categoryLabel: "Аудит и Фоссилизация",
    readTime: "12 мин",
    badge: "Аудит 🎯",
    badgeColor: "rose",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "Larry Selinker (Interlanguage & Fossilization)",
      "ZhaoHong Han (L1 Transfer & Interference)",
    ],
    toc: [
      { id: "audit-overview", title: "01. Обзор диагностического аудита и клинические метрики" },
      { id: "audit-modes", title: "02. Режимы: Все чанки, Флешкарты контраста, Блиц-своп" },
      { id: "audit-categories", title: "03. Кластеры: Кальки L1, Синтаксис, C1-связки и Точность" },
      { id: "audit-content", title: "04. Интерактивная база антидотов и тренировка" },
    ],
  },
  {
    id: "neural-weights",
    slug: "neural-weights",
    href: "/longreads/neural-weights",
    title: "Как Слова и Предложения Хранятся в Памяти: Матрица vs Синаптические Веса и Синтез Речи",
    shortTitle: "Матрица или Веса? Синтез Речи",
    subtitle: "Хранит ли мозг слова в таблице или это веса синапсов? Хронометрия порождения речи Левелта (WEAVER++), непрерывные семантические пространства Хута и инкрементальный синтаксис.",
    description: "Нейробиологический разрыв между компьютерной памятью и распределенными сетями Хебба. Как мозг за 400 мс проходит путь от абстрактной мысли до мышечного выброса звука.",
    category: "neuroscience",
    categoryLabel: "Нейробиология и Память",
    readTime: "18 мин",
    badge: "Исследование 🧬",
    badgeColor: "violet",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "McClelland & Rumelhart (PDP & Connectionism)",
      "Alexander Huth (Nature 2016: Semantic Maps)",
      "Willem Levelt (WEAVER++ Model of Speech)",
      "Adele Goldberg (Construction Grammar)",
      "Collins & Loftus (Spreading Activation)",
    ],
    toc: [
      { id: "nw-sec-1", title: "01. Символьная матрица vs Синаптические веса связей (PDP)" },
      { id: "nw-sec-2", title: "02. Семантические пространства коры (Huth et al., Nature 2016)" },
      { id: "nw-sec-3", title: "03. Хронометрия порождения речи: Модель WEAVER++ Виллема Левелта" },
      { id: "nw-sec-4", title: "04. Spreading Activation, латеральное торможение и ступор B2" },
      { id: "nw-sec-5", title: "05. Инкрементальный синтаксис: Почему мозг не ждет конца фразы" },
      { id: "nw-sec-6", title: "06. Грамматика конструкций Голдберг и протокол тренировки весов" },
    ],
    featured: true,
  },
  {
    id: "direct-thinking",
    slug: "direct-thinking",
    href: "/longreads/direct-thinking",
    title: "Мышление Без Перевода: Психолингвистика Искоренения Субвокального Русского Языка Чанками",
    shortTitle: "Мышление Без Перевода ⚡",
    subtitle: "Почему мозг включает внутренний перевод с русского, как взломать лимит рабочей памяти (4±1 Кована) и говорить на английском с прямым пониманием смыслов.",
    description: "Пересмотренная иерархическая модель (RHM: Kroll & Stewart), ингибиторный контроль Дэвида Грина (ACC/DLPFC) и 4-фазный клинический протокол уничтожения субвокализации.",
    category: "chunks",
    categoryLabel: "Психолингвистика Речи",
    readTime: "17 мин",
    badge: "Практика ⚡",
    badgeColor: "emerald",
    targetLevel: "B2 → C1",
    scientificPillars: [
      "Judith Kroll (Revised Hierarchical Model)",
      "David Green (Inhibitory Control Model)",
      "Alan Baddeley (Working Memory & Phonological Loop)",
      "Alison Wray (Formulaic Sequences)",
      "Michael Lewis (The Lexical Approach)",
    ],
    toc: [
      { id: "dt-sec-1", title: "01. Анатомия ловушки: Модель RHM Кролл и Word Association" },
      { id: "dt-sec-2", title: "02. Катастрофа рабочей памяти: Лимит 4±1 слотов и переполнение петли" },
      { id: "dt-sec-3", title: "03. Чанк как неделимый когнитивный токен: Сжатие N слов в 1 слот" },
      { id: "dt-sec-4", title: "04. Нейробиология ингибирования L1: Контур ACC и DLPFC" },
      { id: "dt-sec-5", title: "05. 4-фазный клинический протокол деинсталляции переводчика" },
      { id: "dt-sec-6", title: "06. Таблица контраста: От кальки L1 к прямому нативному чанку" },
    ],
    featured: true,
  },
] as const;

export function getLongreadBySlug(slug: string): LongreadItem | undefined {
  return LONGREADS.find((item) => item.slug === slug || item.id === slug);
}

export function getLongreadsByCategory(category: string): readonly LongreadItem[] {
  if (category === "all") return LONGREADS;
  return LONGREADS.filter((item) => item.category === category);
}
